// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package health

import (
	"context"

	"github.com/PritOriginal/problem-map-server/internal/usecase"
	mock "github.com/stretchr/testify/mock"
)

// NewMockChecker creates a new instance of MockChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChecker {
	mock := &MockChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChecker is an autogenerated mock type for the Checker type
type MockChecker struct {
	mock.Mock
}

type MockChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChecker) EXPECT() *MockChecker_Expecter {
	return &MockChecker_Expecter{mock: &_m.Mock}
}

// Check provides a mock function for the type MockChecker
func (_mock *MockChecker) Check(ctx context.Context) (usecase.HealthReport, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 usecase.HealthReport
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (usecase.HealthReport, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) usecase.HealthReport); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(usecase.HealthReport)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChecker_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type MockChecker_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockChecker_Expecter) Check(ctx any) *MockChecker_Check_Call {
	return &MockChecker_Check_Call{Call: _e.mock.On("Check", ctx)}
}

func (_c *MockChecker_Check_Call) Run(run func(ctx context.Context)) *MockChecker_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockChecker_Check_Call) Return(healthReport usecase.HealthReport, err error) *MockChecker_Check_Call {
	_c.Call.Return(healthReport, err)
	return _c
}

func (_c *MockChecker_Check_Call) RunAndReturn(run func(ctx context.Context) (usecase.HealthReport, error)) *MockChecker_Check_Call {
	_c.Call.Return(run)
	return _c
}
