// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package organizationsrest

import (
	"context"
	"io"

	"github.com/PritOriginal/problem-map-server/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrganizations creates a new instance of MockOrganizations. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrganizations(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrganizations {
	mock := &MockOrganizations{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrganizations is an autogenerated mock type for the Organizations type
type MockOrganizations struct {
	mock.Mock
}

type MockOrganizations_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrganizations) EXPECT() *MockOrganizations_Expecter {
	return &MockOrganizations_Expecter{mock: &_m.Mock}
}

// AddMember provides a mock function for the type MockOrganizations
func (_mock *MockOrganizations) AddMember(ctx context.Context, orgId int, userId int) error {
	ret := _mock.Called(ctx, orgId, userId)

	if len(ret) == 0 {
		panic("no return value specified for AddMember")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = returnFunc(ctx, orgId, userId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrganizations_AddMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMember'
type MockOrganizations_AddMember_Call struct {
	*mock.Call
}

// AddMember is a helper method to define mock.On call
//   - ctx context.Context
//   - orgId int
//   - userId int
func (_e *MockOrganizations_Expecter) AddMember(ctx any, orgId any, userId any) *MockOrganizations_AddMember_Call {
	return &MockOrganizations_AddMember_Call{Call: _e.mock.On("AddMember", ctx, orgId, userId)}
}

func (_c *MockOrganizations_AddMember_Call) Run(run func(ctx context.Context, orgId int, userId int)) *MockOrganizations_AddMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrganizations_AddMember_Call) Return(err error) *MockOrganizations_AddMember_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrganizations_AddMember_Call) RunAndReturn(run func(ctx context.Context, orgId int, userId int) error) *MockOrganizations_AddMember_Call {
	_c.Call.Return(run)
	return _c
}

// AddResponsibility provides a mock function for the type MockOrganizations
func (_mock *MockOrganizations) AddResponsibility(ctx context.Context, resp models.OrganizationResponsibility) (models.OrganizationResponsibility, error) {
	ret := _mock.Called(ctx, resp)

	if len(ret) == 0 {
		panic("no return value specified for AddResponsibility")
	}

	var r0 models.OrganizationResponsibility
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.OrganizationResponsibility) (models.OrganizationResponsibility, error)); ok {
		return returnFunc(ctx, resp)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.OrganizationResponsibility) models.OrganizationResponsibility); ok {
		r0 = returnFunc(ctx, resp)
	} else {
		r0 = ret.Get(0).(models.OrganizationResponsibility)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.OrganizationResponsibility) error); ok {
		r1 = returnFunc(ctx, resp)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizations_AddResponsibility_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddResponsibility'
type MockOrganizations_AddResponsibility_Call struct {
	*mock.Call
}

// AddResponsibility is a helper method to define mock.On call
//   - ctx context.Context
//   - resp models.OrganizationResponsibility
func (_e *MockOrganizations_Expecter) AddResponsibility(ctx any, resp any) *MockOrganizations_AddResponsibility_Call {
	return &MockOrganizations_AddResponsibility_Call{Call: _e.mock.On("AddResponsibility", ctx, resp)}
}

func (_c *MockOrganizations_AddResponsibility_Call) Run(run func(ctx context.Context, resp models.OrganizationResponsibility)) *MockOrganizations_AddResponsibility_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.OrganizationResponsibility
		if args[1] != nil {
			arg1 = args[1].(models.OrganizationResponsibility)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrganizations_AddResponsibility_Call) Return(organizationResponsibility models.OrganizationResponsibility, err error) *MockOrganizations_AddResponsibility_Call {
	_c.Call.Return(organizationResponsibility, err)
	return _c
}

func (_c *MockOrganizations_AddResponsibility_Call) RunAndReturn(run func(ctx context.Context, resp models.OrganizationResponsibility) (models.OrganizationResponsibility, error)) *MockOrganizations_AddResponsibility_Call {
	_c.Call.Return(run)
	return _c
}

// Assign provides a mock function for the type MockOrganizations
func (_mock *MockOrganizations) Assign(ctx context.Context, markId int, orgId int) (models.Mark, error) {
	ret := _mock.Called(ctx, markId, orgId)

	if len(ret) == 0 {
		panic("no return value specified for Assign")
	}

	var r0 models.Mark
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) (models.Mark, error)); ok {
		return returnFunc(ctx, markId, orgId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) models.Mark); ok {
		r0 = returnFunc(ctx, markId, orgId)
	} else {
		r0 = ret.Get(0).(models.Mark)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, markId, orgId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizations_Assign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Assign'
type MockOrganizations_Assign_Call struct {
	*mock.Call
}

// Assign is a helper method to define mock.On call
//   - ctx context.Context
//   - markId int
//   - orgId int
func (_e *MockOrganizations_Expecter) Assign(ctx any, markId any, orgId any) *MockOrganizations_Assign_Call {
	return &MockOrganizations_Assign_Call{Call: _e.mock.On("Assign", ctx, markId, orgId)}
}

func (_c *MockOrganizations_Assign_Call) Run(run func(ctx context.Context, markId int, orgId int)) *MockOrganizations_Assign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrganizations_Assign_Call) Return(mark models.Mark, err error) *MockOrganizations_Assign_Call {
	_c.Call.Return(mark, err)
	return _c
}

func (_c *MockOrganizations_Assign_Call) RunAndReturn(run func(ctx context.Context, markId int, orgId int) (models.Mark, error)) *MockOrganizations_Assign_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockOrganizations
func (_mock *MockOrganizations) Create(ctx context.Context, org models.Organization) (models.Organization, error) {
	ret := _mock.Called(ctx, org)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.Organization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Organization) (models.Organization, error)); ok {
		return returnFunc(ctx, org)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Organization) models.Organization); ok {
		r0 = returnFunc(ctx, org)
	} else {
		r0 = ret.Get(0).(models.Organization)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Organization) error); ok {
		r1 = returnFunc(ctx, org)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizations_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOrganizations_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - org models.Organization
func (_e *MockOrganizations_Expecter) Create(ctx any, org any) *MockOrganizations_Create_Call {
	return &MockOrganizations_Create_Call{Call: _e.mock.On("Create", ctx, org)}
}

func (_c *MockOrganizations_Create_Call) Run(run func(ctx context.Context, org models.Organization)) *MockOrganizations_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Organization
		if args[1] != nil {
			arg1 = args[1].(models.Organization)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrganizations_Create_Call) Return(organization models.Organization, err error) *MockOrganizations_Create_Call {
	_c.Call.Return(organization, err)
	return _c
}

func (_c *MockOrganizations_Create_Call) RunAndReturn(run func(ctx context.Context, org models.Organization) (models.Organization, error)) *MockOrganizations_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockOrganizations
func (_mock *MockOrganizations) Get(ctx context.Context, id int) (models.OrganizationDetails, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 models.OrganizationDetails
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (models.OrganizationDetails, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) models.OrganizationDetails); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(models.OrganizationDetails)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizations_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockOrganizations_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockOrganizations_Expecter) Get(ctx any, id any) *MockOrganizations_Get_Call {
	return &MockOrganizations_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockOrganizations_Get_Call) Run(run func(ctx context.Context, id int)) *MockOrganizations_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrganizations_Get_Call) Return(organizationDetails models.OrganizationDetails, err error) *MockOrganizations_Get_Call {
	_c.Call.Return(organizationDetails, err)
	return _c
}

func (_c *MockOrganizations_Get_Call) RunAndReturn(run func(ctx context.Context, id int) (models.OrganizationDetails, error)) *MockOrganizations_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetMine provides a mock function for the type MockOrganizations
func (_mock *MockOrganizations) GetMine(ctx context.Context, userId int) (models.OrganizationDetails, error) {
	ret := _mock.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetMine")
	}

	var r0 models.OrganizationDetails
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (models.OrganizationDetails, error)); ok {
		return returnFunc(ctx, userId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) models.OrganizationDetails); ok {
		r0 = returnFunc(ctx, userId)
	} else {
		r0 = ret.Get(0).(models.OrganizationDetails)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizations_GetMine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMine'
type MockOrganizations_GetMine_Call struct {
	*mock.Call
}

// GetMine is a helper method to define mock.On call
//   - ctx context.Context
//   - userId int
func (_e *MockOrganizations_Expecter) GetMine(ctx any, userId any) *MockOrganizations_GetMine_Call {
	return &MockOrganizations_GetMine_Call{Call: _e.mock.On("GetMine", ctx, userId)}
}

func (_c *MockOrganizations_GetMine_Call) Run(run func(ctx context.Context, userId int)) *MockOrganizations_GetMine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrganizations_GetMine_Call) Return(organizationDetails models.OrganizationDetails, err error) *MockOrganizations_GetMine_Call {
	_c.Call.Return(organizationDetails, err)
	return _c
}

func (_c *MockOrganizations_GetMine_Call) RunAndReturn(run func(ctx context.Context, userId int) (models.OrganizationDetails, error)) *MockOrganizations_GetMine_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockOrganizations
func (_mock *MockOrganizations) List(ctx context.Context) ([]models.OrganizationRef, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.OrganizationRef
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.OrganizationRef, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.OrganizationRef); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.OrganizationRef)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizations_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockOrganizations_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOrganizations_Expecter) List(ctx any) *MockOrganizations_List_Call {
	return &MockOrganizations_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockOrganizations_List_Call) Run(run func(ctx context.Context)) *MockOrganizations_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOrganizations_List_Call) Return(organizationRefs []models.OrganizationRef, err error) *MockOrganizations_List_Call {
	_c.Call.Return(organizationRefs, err)
	return _c
}

func (_c *MockOrganizations_List_Call) RunAndReturn(run func(ctx context.Context) ([]models.OrganizationRef, error)) *MockOrganizations_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListMarks provides a mock function for the type MockOrganizations
func (_mock *MockOrganizations) ListMarks(ctx context.Context, actor models.Actor, orgId int, filters models.GetOrganizationMarksFilters) (models.Page[models.Mark], error) {
	ret := _mock.Called(ctx, actor, orgId, filters)

	if len(ret) == 0 {
		panic("no return value specified for ListMarks")
	}

	var r0 models.Page[models.Mark]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Actor, int, models.GetOrganizationMarksFilters) (models.Page[models.Mark], error)); ok {
		return returnFunc(ctx, actor, orgId, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Actor, int, models.GetOrganizationMarksFilters) models.Page[models.Mark]); ok {
		r0 = returnFunc(ctx, actor, orgId, filters)
	} else {
		r0 = ret.Get(0).(models.Page[models.Mark])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Actor, int, models.GetOrganizationMarksFilters) error); ok {
		r1 = returnFunc(ctx, actor, orgId, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizations_ListMarks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMarks'
type MockOrganizations_ListMarks_Call struct {
	*mock.Call
}

// ListMarks is a helper method to define mock.On call
//   - ctx context.Context
//   - actor models.Actor
//   - orgId int
//   - filters models.GetOrganizationMarksFilters
func (_e *MockOrganizations_Expecter) ListMarks(ctx any, actor any, orgId any, filters any) *MockOrganizations_ListMarks_Call {
	return &MockOrganizations_ListMarks_Call{Call: _e.mock.On("ListMarks", ctx, actor, orgId, filters)}
}

func (_c *MockOrganizations_ListMarks_Call) Run(run func(ctx context.Context, actor models.Actor, orgId int, filters models.GetOrganizationMarksFilters)) *MockOrganizations_ListMarks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Actor
		if args[1] != nil {
			arg1 = args[1].(models.Actor)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 models.GetOrganizationMarksFilters
		if args[3] != nil {
			arg3 = args[3].(models.GetOrganizationMarksFilters)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockOrganizations_ListMarks_Call) Return(page models.Page[models.Mark], err error) *MockOrganizations_ListMarks_Call {
	_c.Call.Return(page, err)
	return _c
}

func (_c *MockOrganizations_ListMarks_Call) RunAndReturn(run func(ctx context.Context, actor models.Actor, orgId int, filters models.GetOrganizationMarksFilters) (models.Page[models.Mark], error)) *MockOrganizations_ListMarks_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveMember provides a mock function for the type MockOrganizations
func (_mock *MockOrganizations) RemoveMember(ctx context.Context, orgId int, userId int) error {
	ret := _mock.Called(ctx, orgId, userId)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = returnFunc(ctx, orgId, userId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrganizations_RemoveMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveMember'
type MockOrganizations_RemoveMember_Call struct {
	*mock.Call
}

// RemoveMember is a helper method to define mock.On call
//   - ctx context.Context
//   - orgId int
//   - userId int
func (_e *MockOrganizations_Expecter) RemoveMember(ctx any, orgId any, userId any) *MockOrganizations_RemoveMember_Call {
	return &MockOrganizations_RemoveMember_Call{Call: _e.mock.On("RemoveMember", ctx, orgId, userId)}
}

func (_c *MockOrganizations_RemoveMember_Call) Run(run func(ctx context.Context, orgId int, userId int)) *MockOrganizations_RemoveMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrganizations_RemoveMember_Call) Return(err error) *MockOrganizations_RemoveMember_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrganizations_RemoveMember_Call) RunAndReturn(run func(ctx context.Context, orgId int, userId int) error) *MockOrganizations_RemoveMember_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveResponsibility provides a mock function for the type MockOrganizations
func (_mock *MockOrganizations) RemoveResponsibility(ctx context.Context, resp models.OrganizationResponsibility) error {
	ret := _mock.Called(ctx, resp)

	if len(ret) == 0 {
		panic("no return value specified for RemoveResponsibility")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.OrganizationResponsibility) error); ok {
		r0 = returnFunc(ctx, resp)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrganizations_RemoveResponsibility_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveResponsibility'
type MockOrganizations_RemoveResponsibility_Call struct {
	*mock.Call
}

// RemoveResponsibility is a helper method to define mock.On call
//   - ctx context.Context
//   - resp models.OrganizationResponsibility
func (_e *MockOrganizations_Expecter) RemoveResponsibility(ctx any, resp any) *MockOrganizations_RemoveResponsibility_Call {
	return &MockOrganizations_RemoveResponsibility_Call{Call: _e.mock.On("RemoveResponsibility", ctx, resp)}
}

func (_c *MockOrganizations_RemoveResponsibility_Call) Run(run func(ctx context.Context, resp models.OrganizationResponsibility)) *MockOrganizations_RemoveResponsibility_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.OrganizationResponsibility
		if args[1] != nil {
			arg1 = args[1].(models.OrganizationResponsibility)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrganizations_RemoveResponsibility_Call) Return(err error) *MockOrganizations_RemoveResponsibility_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrganizations_RemoveResponsibility_Call) RunAndReturn(run func(ctx context.Context, resp models.OrganizationResponsibility) error) *MockOrganizations_RemoveResponsibility_Call {
	_c.Call.Return(run)
	return _c
}

// Resolve provides a mock function for the type MockOrganizations
func (_mock *MockOrganizations) Resolve(ctx context.Context, actor models.Actor, markId int, comment string, photos []io.Reader) (models.Mark, error) {
	ret := _mock.Called(ctx, actor, markId, comment, photos)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 models.Mark
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Actor, int, string, []io.Reader) (models.Mark, error)); ok {
		return returnFunc(ctx, actor, markId, comment, photos)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Actor, int, string, []io.Reader) models.Mark); ok {
		r0 = returnFunc(ctx, actor, markId, comment, photos)
	} else {
		r0 = ret.Get(0).(models.Mark)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Actor, int, string, []io.Reader) error); ok {
		r1 = returnFunc(ctx, actor, markId, comment, photos)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizations_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockOrganizations_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - ctx context.Context
//   - actor models.Actor
//   - markId int
//   - comment string
//   - photos []io.Reader
func (_e *MockOrganizations_Expecter) Resolve(ctx any, actor any, markId any, comment any, photos any) *MockOrganizations_Resolve_Call {
	return &MockOrganizations_Resolve_Call{Call: _e.mock.On("Resolve", ctx, actor, markId, comment, photos)}
}

func (_c *MockOrganizations_Resolve_Call) Run(run func(ctx context.Context, actor models.Actor, markId int, comment string, photos []io.Reader)) *MockOrganizations_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Actor
		if args[1] != nil {
			arg1 = args[1].(models.Actor)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []io.Reader
		if args[4] != nil {
			arg4 = args[4].([]io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockOrganizations_Resolve_Call) Return(mark models.Mark, err error) *MockOrganizations_Resolve_Call {
	_c.Call.Return(mark, err)
	return _c
}

func (_c *MockOrganizations_Resolve_Call) RunAndReturn(run func(ctx context.Context, actor models.Actor, markId int, comment string, photos []io.Reader) (models.Mark, error)) *MockOrganizations_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockOrganizations
func (_mock *MockOrganizations) Start(ctx context.Context, actor models.Actor, markId int) (models.Mark, error) {
	ret := _mock.Called(ctx, actor, markId)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 models.Mark
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Actor, int) (models.Mark, error)); ok {
		return returnFunc(ctx, actor, markId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Actor, int) models.Mark); ok {
		r0 = returnFunc(ctx, actor, markId)
	} else {
		r0 = ret.Get(0).(models.Mark)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Actor, int) error); ok {
		r1 = returnFunc(ctx, actor, markId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizations_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockOrganizations_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - actor models.Actor
//   - markId int
func (_e *MockOrganizations_Expecter) Start(ctx any, actor any, markId any) *MockOrganizations_Start_Call {
	return &MockOrganizations_Start_Call{Call: _e.mock.On("Start", ctx, actor, markId)}
}

func (_c *MockOrganizations_Start_Call) Run(run func(ctx context.Context, actor models.Actor, markId int)) *MockOrganizations_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Actor
		if args[1] != nil {
			arg1 = args[1].(models.Actor)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrganizations_Start_Call) Return(mark models.Mark, err error) *MockOrganizations_Start_Call {
	_c.Call.Return(mark, err)
	return _c
}

func (_c *MockOrganizations_Start_Call) RunAndReturn(run func(ctx context.Context, actor models.Actor, markId int) (models.Mark, error)) *MockOrganizations_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockOrganizations
func (_mock *MockOrganizations) Update(ctx context.Context, id int, upd models.OrganizationUpdate) (models.Organization, error) {
	ret := _mock.Called(ctx, id, upd)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 models.Organization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.OrganizationUpdate) (models.Organization, error)); ok {
		return returnFunc(ctx, id, upd)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.OrganizationUpdate) models.Organization); ok {
		r0 = returnFunc(ctx, id, upd)
	} else {
		r0 = ret.Get(0).(models.Organization)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, models.OrganizationUpdate) error); ok {
		r1 = returnFunc(ctx, id, upd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizations_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockOrganizations_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - upd models.OrganizationUpdate
func (_e *MockOrganizations_Expecter) Update(ctx any, id any, upd any) *MockOrganizations_Update_Call {
	return &MockOrganizations_Update_Call{Call: _e.mock.On("Update", ctx, id, upd)}
}

func (_c *MockOrganizations_Update_Call) Run(run func(ctx context.Context, id int, upd models.OrganizationUpdate)) *MockOrganizations_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 models.OrganizationUpdate
		if args[2] != nil {
			arg2 = args[2].(models.OrganizationUpdate)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrganizations_Update_Call) Return(organization models.Organization, err error) *MockOrganizations_Update_Call {
	_c.Call.Return(organization, err)
	return _c
}

func (_c *MockOrganizations_Update_Call) RunAndReturn(run func(ctx context.Context, id int, upd models.OrganizationUpdate) (models.Organization, error)) *MockOrganizations_Update_Call {
	_c.Call.Return(run)
	return _c
}
