// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package authrest

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAuth creates a new instance of MockAuth. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuth(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuth {
	mock := &MockAuth{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuth is an autogenerated mock type for the Auth type
type MockAuth struct {
	mock.Mock
}

type MockAuth_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuth) EXPECT() *MockAuth_Expecter {
	return &MockAuth_Expecter{mock: &_m.Mock}
}

// RefreshTokens provides a mock function for the type MockAuth
func (_mock *MockAuth) RefreshTokens(ctx context.Context, refreshToken string) (string, string, error) {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshTokens")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, string, error)); ok {
		return returnFunc(ctx, refreshToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = returnFunc(ctx, refreshToken)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, refreshToken)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAuth_RefreshTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshTokens'
type MockAuth_RefreshTokens_Call struct {
	*mock.Call
}

// RefreshTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockAuth_Expecter) RefreshTokens(ctx interface{}, refreshToken interface{}) *MockAuth_RefreshTokens_Call {
	return &MockAuth_RefreshTokens_Call{Call: _e.mock.On("RefreshTokens", ctx, refreshToken)}
}

func (_c *MockAuth_RefreshTokens_Call) Run(run func(ctx context.Context, refreshToken string)) *MockAuth_RefreshTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuth_RefreshTokens_Call) Return(s string, s1 string, err error) *MockAuth_RefreshTokens_Call {
	_c.Call.Return(s, s1, err)
	return _c
}

func (_c *MockAuth_RefreshTokens_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) (string, string, error)) *MockAuth_RefreshTokens_Call {
	_c.Call.Return(run)
	return _c
}

// SignIn provides a mock function for the type MockAuth
func (_mock *MockAuth) SignIn(ctx context.Context, username string, password string) (string, string, error) {
	ret := _mock.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for SignIn")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, string, error)); ok {
		return returnFunc(ctx, username, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, username, password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = returnFunc(ctx, username, password)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, username, password)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAuth_SignIn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignIn'
type MockAuth_SignIn_Call struct {
	*mock.Call
}

// SignIn is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *MockAuth_Expecter) SignIn(ctx interface{}, username interface{}, password interface{}) *MockAuth_SignIn_Call {
	return &MockAuth_SignIn_Call{Call: _e.mock.On("SignIn", ctx, username, password)}
}

func (_c *MockAuth_SignIn_Call) Run(run func(ctx context.Context, username string, password string)) *MockAuth_SignIn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuth_SignIn_Call) Return(s string, s1 string, err error) *MockAuth_SignIn_Call {
	_c.Call.Return(s, s1, err)
	return _c
}

func (_c *MockAuth_SignIn_Call) RunAndReturn(run func(ctx context.Context, username string, password string) (string, string, error)) *MockAuth_SignIn_Call {
	_c.Call.Return(run)
	return _c
}

// SignUp provides a mock function for the type MockAuth
func (_mock *MockAuth) SignUp(ctx context.Context, name string, username string, password string) (int64, error) {
	ret := _mock.Called(ctx, name, username, password)

	if len(ret) == 0 {
		panic("no return value specified for SignUp")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (int64, error)); ok {
		return returnFunc(ctx, name, username, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) int64); ok {
		r0 = returnFunc(ctx, name, username, password)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, name, username, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuth_SignUp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignUp'
type MockAuth_SignUp_Call struct {
	*mock.Call
}

// SignUp is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - username string
//   - password string
func (_e *MockAuth_Expecter) SignUp(ctx interface{}, name interface{}, username interface{}, password interface{}) *MockAuth_SignUp_Call {
	return &MockAuth_SignUp_Call{Call: _e.mock.On("SignUp", ctx, name, username, password)}
}

func (_c *MockAuth_SignUp_Call) Run(run func(ctx context.Context, name string, username string, password string)) *MockAuth_SignUp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAuth_SignUp_Call) Return(n int64, err error) *MockAuth_SignUp_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockAuth_SignUp_Call) RunAndReturn(run func(ctx context.Context, name string, username string, password string) (int64, error)) *MockAuth_SignUp_Call {
	_c.Call.Return(run)
	return _c
}
