// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package apikeysrest

import (
	"context"

	"github.com/PritOriginal/problem-map-server/internal/models"
	"github.com/guregu/null/v6"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAPIKeys creates a new instance of MockAPIKeys. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPIKeys(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPIKeys {
	mock := &MockAPIKeys{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAPIKeys is an autogenerated mock type for the APIKeys type
type MockAPIKeys struct {
	mock.Mock
}

type MockAPIKeys_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPIKeys) EXPECT() *MockAPIKeys_Expecter {
	return &MockAPIKeys_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockAPIKeys
func (_mock *MockAPIKeys) Create(ctx context.Context, actor models.Actor, name string, expiresAt null.Time) (models.APIKey, string, error) {
	ret := _mock.Called(ctx, actor, name, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.APIKey
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Actor, string, null.Time) (models.APIKey, string, error)); ok {
		return returnFunc(ctx, actor, name, expiresAt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Actor, string, null.Time) models.APIKey); ok {
		r0 = returnFunc(ctx, actor, name, expiresAt)
	} else {
		r0 = ret.Get(0).(models.APIKey)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Actor, string, null.Time) string); ok {
		r1 = returnFunc(ctx, actor, name, expiresAt)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, models.Actor, string, null.Time) error); ok {
		r2 = returnFunc(ctx, actor, name, expiresAt)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAPIKeys_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAPIKeys_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - actor models.Actor
//   - name string
//   - expiresAt null.Time
func (_e *MockAPIKeys_Expecter) Create(ctx any, actor any, name any, expiresAt any) *MockAPIKeys_Create_Call {
	return &MockAPIKeys_Create_Call{Call: _e.mock.On("Create", ctx, actor, name, expiresAt)}
}

func (_c *MockAPIKeys_Create_Call) Run(run func(ctx context.Context, actor models.Actor, name string, expiresAt null.Time)) *MockAPIKeys_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Actor
		if args[1] != nil {
			arg1 = args[1].(models.Actor)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 null.Time
		if args[3] != nil {
			arg3 = args[3].(null.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAPIKeys_Create_Call) Return(aPIKey models.APIKey, s string, err error) *MockAPIKeys_Create_Call {
	_c.Call.Return(aPIKey, s, err)
	return _c
}

func (_c *MockAPIKeys_Create_Call) RunAndReturn(run func(ctx context.Context, actor models.Actor, name string, expiresAt null.Time) (models.APIKey, string, error)) *MockAPIKeys_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockAPIKeys
func (_mock *MockAPIKeys) List(ctx context.Context, actor models.Actor, all bool) ([]models.APIKey, error) {
	ret := _mock.Called(ctx, actor, all)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.APIKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Actor, bool) ([]models.APIKey, error)); ok {
		return returnFunc(ctx, actor, all)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Actor, bool) []models.APIKey); ok {
		r0 = returnFunc(ctx, actor, all)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.APIKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Actor, bool) error); ok {
		r1 = returnFunc(ctx, actor, all)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIKeys_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockAPIKeys_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - actor models.Actor
//   - all bool
func (_e *MockAPIKeys_Expecter) List(ctx any, actor any, all any) *MockAPIKeys_List_Call {
	return &MockAPIKeys_List_Call{Call: _e.mock.On("List", ctx, actor, all)}
}

func (_c *MockAPIKeys_List_Call) Run(run func(ctx context.Context, actor models.Actor, all bool)) *MockAPIKeys_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Actor
		if args[1] != nil {
			arg1 = args[1].(models.Actor)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAPIKeys_List_Call) Return(aPIKeys []models.APIKey, err error) *MockAPIKeys_List_Call {
	_c.Call.Return(aPIKeys, err)
	return _c
}

func (_c *MockAPIKeys_List_Call) RunAndReturn(run func(ctx context.Context, actor models.Actor, all bool) ([]models.APIKey, error)) *MockAPIKeys_List_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function for the type MockAPIKeys
func (_mock *MockAPIKeys) Revoke(ctx context.Context, actor models.Actor, id int) error {
	ret := _mock.Called(ctx, actor, id)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Actor, int) error); ok {
		r0 = returnFunc(ctx, actor, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAPIKeys_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockAPIKeys_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - actor models.Actor
//   - id int
func (_e *MockAPIKeys_Expecter) Revoke(ctx any, actor any, id any) *MockAPIKeys_Revoke_Call {
	return &MockAPIKeys_Revoke_Call{Call: _e.mock.On("Revoke", ctx, actor, id)}
}

func (_c *MockAPIKeys_Revoke_Call) Run(run func(ctx context.Context, actor models.Actor, id int)) *MockAPIKeys_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Actor
		if args[1] != nil {
			arg1 = args[1].(models.Actor)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAPIKeys_Revoke_Call) Return(err error) *MockAPIKeys_Revoke_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAPIKeys_Revoke_Call) RunAndReturn(run func(ctx context.Context, actor models.Actor, id int) error) *MockAPIKeys_Revoke_Call {
	_c.Call.Return(run)
	return _c
}
