// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package marksrest

import (
	"context"
	"io"

	"github.com/PritOriginal/problem-map-server/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMarks creates a new instance of MockMarks. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMarks(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMarks {
	mock := &MockMarks{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMarks is an autogenerated mock type for the Marks type
type MockMarks struct {
	mock.Mock
}

type MockMarks_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMarks) EXPECT() *MockMarks_Expecter {
	return &MockMarks_Expecter{mock: &_m.Mock}
}

// AddMark provides a mock function for the type MockMarks
func (_mock *MockMarks) AddMark(ctx context.Context, mark models.Mark, photos []io.Reader, force bool) (int64, error) {
	ret := _mock.Called(ctx, mark, photos, force)

	if len(ret) == 0 {
		panic("no return value specified for AddMark")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Mark, []io.Reader, bool) (int64, error)); ok {
		return returnFunc(ctx, mark, photos, force)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Mark, []io.Reader, bool) int64); ok {
		r0 = returnFunc(ctx, mark, photos, force)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Mark, []io.Reader, bool) error); ok {
		r1 = returnFunc(ctx, mark, photos, force)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMarks_AddMark_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMark'
type MockMarks_AddMark_Call struct {
	*mock.Call
}

// AddMark is a helper method to define mock.On call
//   - ctx context.Context
//   - mark models.Mark
//   - photos []io.Reader
//   - force bool
func (_e *MockMarks_Expecter) AddMark(ctx any, mark any, photos any, force any) *MockMarks_AddMark_Call {
	return &MockMarks_AddMark_Call{Call: _e.mock.On("AddMark", ctx, mark, photos, force)}
}

func (_c *MockMarks_AddMark_Call) Run(run func(ctx context.Context, mark models.Mark, photos []io.Reader, force bool)) *MockMarks_AddMark_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Mark
		if args[1] != nil {
			arg1 = args[1].(models.Mark)
		}
		var arg2 []io.Reader
		if args[2] != nil {
			arg2 = args[2].([]io.Reader)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMarks_AddMark_Call) Return(n int64, err error) *MockMarks_AddMark_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockMarks_AddMark_Call) RunAndReturn(run func(ctx context.Context, mark models.Mark, photos []io.Reader, force bool) (int64, error)) *MockMarks_AddMark_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMark provides a mock function for the type MockMarks
func (_mock *MockMarks) DeleteMark(ctx context.Context, actor models.Actor, markId int) error {
	ret := _mock.Called(ctx, actor, markId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMark")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Actor, int) error); ok {
		r0 = returnFunc(ctx, actor, markId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMarks_DeleteMark_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMark'
type MockMarks_DeleteMark_Call struct {
	*mock.Call
}

// DeleteMark is a helper method to define mock.On call
//   - ctx context.Context
//   - actor models.Actor
//   - markId int
func (_e *MockMarks_Expecter) DeleteMark(ctx any, actor any, markId any) *MockMarks_DeleteMark_Call {
	return &MockMarks_DeleteMark_Call{Call: _e.mock.On("DeleteMark", ctx, actor, markId)}
}

func (_c *MockMarks_DeleteMark_Call) Run(run func(ctx context.Context, actor models.Actor, markId int)) *MockMarks_DeleteMark_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Actor
		if args[1] != nil {
			arg1 = args[1].(models.Actor)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMarks_DeleteMark_Call) Return(err error) *MockMarks_DeleteMark_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMarks_DeleteMark_Call) RunAndReturn(run func(ctx context.Context, actor models.Actor, markId int) error) *MockMarks_DeleteMark_Call {
	_c.Call.Return(run)
	return _c
}

// FindSimilarMarks provides a mock function for the type MockMarks
func (_mock *MockMarks) FindSimilarMarks(ctx context.Context, filters models.GetSimilarMarksFilters) ([]models.MarkWithDistance, error) {
	ret := _mock.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for FindSimilarMarks")
	}

	var r0 []models.MarkWithDistance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetSimilarMarksFilters) ([]models.MarkWithDistance, error)); ok {
		return returnFunc(ctx, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetSimilarMarksFilters) []models.MarkWithDistance); ok {
		r0 = returnFunc(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.MarkWithDistance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.GetSimilarMarksFilters) error); ok {
		r1 = returnFunc(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMarks_FindSimilarMarks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSimilarMarks'
type MockMarks_FindSimilarMarks_Call struct {
	*mock.Call
}

// FindSimilarMarks is a helper method to define mock.On call
//   - ctx context.Context
//   - filters models.GetSimilarMarksFilters
func (_e *MockMarks_Expecter) FindSimilarMarks(ctx any, filters any) *MockMarks_FindSimilarMarks_Call {
	return &MockMarks_FindSimilarMarks_Call{Call: _e.mock.On("FindSimilarMarks", ctx, filters)}
}

func (_c *MockMarks_FindSimilarMarks_Call) Run(run func(ctx context.Context, filters models.GetSimilarMarksFilters)) *MockMarks_FindSimilarMarks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.GetSimilarMarksFilters
		if args[1] != nil {
			arg1 = args[1].(models.GetSimilarMarksFilters)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMarks_FindSimilarMarks_Call) Return(markWithDistances []models.MarkWithDistance, err error) *MockMarks_FindSimilarMarks_Call {
	_c.Call.Return(markWithDistances, err)
	return _c
}

func (_c *MockMarks_FindSimilarMarks_Call) RunAndReturn(run func(ctx context.Context, filters models.GetSimilarMarksFilters) ([]models.MarkWithDistance, error)) *MockMarks_FindSimilarMarks_Call {
	_c.Call.Return(run)
	return _c
}

// FollowMark provides a mock function for the type MockMarks
func (_mock *MockMarks) FollowMark(ctx context.Context, userId int, markId int) error {
	ret := _mock.Called(ctx, userId, markId)

	if len(ret) == 0 {
		panic("no return value specified for FollowMark")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = returnFunc(ctx, userId, markId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMarks_FollowMark_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FollowMark'
type MockMarks_FollowMark_Call struct {
	*mock.Call
}

// FollowMark is a helper method to define mock.On call
//   - ctx context.Context
//   - userId int
//   - markId int
func (_e *MockMarks_Expecter) FollowMark(ctx any, userId any, markId any) *MockMarks_FollowMark_Call {
	return &MockMarks_FollowMark_Call{Call: _e.mock.On("FollowMark", ctx, userId, markId)}
}

func (_c *MockMarks_FollowMark_Call) Run(run func(ctx context.Context, userId int, markId int)) *MockMarks_FollowMark_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMarks_FollowMark_Call) Return(err error) *MockMarks_FollowMark_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMarks_FollowMark_Call) RunAndReturn(run func(ctx context.Context, userId int, markId int) error) *MockMarks_FollowMark_Call {
	_c.Call.Return(run)
	return _c
}

// GetMarkById provides a mock function for the type MockMarks
func (_mock *MockMarks) GetMarkById(ctx context.Context, id int) (models.Mark, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetMarkById")
	}

	var r0 models.Mark
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (models.Mark, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) models.Mark); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Mark)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMarks_GetMarkById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMarkById'
type MockMarks_GetMarkById_Call struct {
	*mock.Call
}

// GetMarkById is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockMarks_Expecter) GetMarkById(ctx any, id any) *MockMarks_GetMarkById_Call {
	return &MockMarks_GetMarkById_Call{Call: _e.mock.On("GetMarkById", ctx, id)}
}

func (_c *MockMarks_GetMarkById_Call) Run(run func(ctx context.Context, id int)) *MockMarks_GetMarkById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMarks_GetMarkById_Call) Return(mark models.Mark, err error) *MockMarks_GetMarkById_Call {
	_c.Call.Return(mark, err)
	return _c
}

func (_c *MockMarks_GetMarkById_Call) RunAndReturn(run func(ctx context.Context, id int) (models.Mark, error)) *MockMarks_GetMarkById_Call {
	_c.Call.Return(run)
	return _c
}

// GetMarkStatusHistoryByMarkId provides a mock function for the type MockMarks
func (_mock *MockMarks) GetMarkStatusHistoryByMarkId(ctx context.Context, markId int, withChecks bool) ([]models.MarkStatusHistoryItem, error) {
	ret := _mock.Called(ctx, markId, withChecks)

	if len(ret) == 0 {
		panic("no return value specified for GetMarkStatusHistoryByMarkId")
	}

	var r0 []models.MarkStatusHistoryItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, bool) ([]models.MarkStatusHistoryItem, error)); ok {
		return returnFunc(ctx, markId, withChecks)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, bool) []models.MarkStatusHistoryItem); ok {
		r0 = returnFunc(ctx, markId, withChecks)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.MarkStatusHistoryItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, bool) error); ok {
		r1 = returnFunc(ctx, markId, withChecks)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMarks_GetMarkStatusHistoryByMarkId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMarkStatusHistoryByMarkId'
type MockMarks_GetMarkStatusHistoryByMarkId_Call struct {
	*mock.Call
}

// GetMarkStatusHistoryByMarkId is a helper method to define mock.On call
//   - ctx context.Context
//   - markId int
//   - withChecks bool
func (_e *MockMarks_Expecter) GetMarkStatusHistoryByMarkId(ctx any, markId any, withChecks any) *MockMarks_GetMarkStatusHistoryByMarkId_Call {
	return &MockMarks_GetMarkStatusHistoryByMarkId_Call{Call: _e.mock.On("GetMarkStatusHistoryByMarkId", ctx, markId, withChecks)}
}

func (_c *MockMarks_GetMarkStatusHistoryByMarkId_Call) Run(run func(ctx context.Context, markId int, withChecks bool)) *MockMarks_GetMarkStatusHistoryByMarkId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMarks_GetMarkStatusHistoryByMarkId_Call) Return(markStatusHistoryItems []models.MarkStatusHistoryItem, err error) *MockMarks_GetMarkStatusHistoryByMarkId_Call {
	_c.Call.Return(markStatusHistoryItems, err)
	return _c
}

func (_c *MockMarks_GetMarkStatusHistoryByMarkId_Call) RunAndReturn(run func(ctx context.Context, markId int, withChecks bool) ([]models.MarkStatusHistoryItem, error)) *MockMarks_GetMarkStatusHistoryByMarkId_Call {
	_c.Call.Return(run)
	return _c
}

// GetMarkStatuses provides a mock function for the type MockMarks
func (_mock *MockMarks) GetMarkStatuses(ctx context.Context, lang models.Lang) ([]models.MarkStatus, error) {
	ret := _mock.Called(ctx, lang)

	if len(ret) == 0 {
		panic("no return value specified for GetMarkStatuses")
	}

	var r0 []models.MarkStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Lang) ([]models.MarkStatus, error)); ok {
		return returnFunc(ctx, lang)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Lang) []models.MarkStatus); ok {
		r0 = returnFunc(ctx, lang)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.MarkStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Lang) error); ok {
		r1 = returnFunc(ctx, lang)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMarks_GetMarkStatuses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMarkStatuses'
type MockMarks_GetMarkStatuses_Call struct {
	*mock.Call
}

// GetMarkStatuses is a helper method to define mock.On call
//   - ctx context.Context
//   - lang models.Lang
func (_e *MockMarks_Expecter) GetMarkStatuses(ctx any, lang any) *MockMarks_GetMarkStatuses_Call {
	return &MockMarks_GetMarkStatuses_Call{Call: _e.mock.On("GetMarkStatuses", ctx, lang)}
}

func (_c *MockMarks_GetMarkStatuses_Call) Run(run func(ctx context.Context, lang models.Lang)) *MockMarks_GetMarkStatuses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Lang
		if args[1] != nil {
			arg1 = args[1].(models.Lang)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMarks_GetMarkStatuses_Call) Return(markStatuss []models.MarkStatus, err error) *MockMarks_GetMarkStatuses_Call {
	_c.Call.Return(markStatuss, err)
	return _c
}

func (_c *MockMarks_GetMarkStatuses_Call) RunAndReturn(run func(ctx context.Context, lang models.Lang) ([]models.MarkStatus, error)) *MockMarks_GetMarkStatuses_Call {
	_c.Call.Return(run)
	return _c
}

// GetMarkTypes provides a mock function for the type MockMarks
func (_mock *MockMarks) GetMarkTypes(ctx context.Context, lang models.Lang) ([]models.MarkType, error) {
	ret := _mock.Called(ctx, lang)

	if len(ret) == 0 {
		panic("no return value specified for GetMarkTypes")
	}

	var r0 []models.MarkType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Lang) ([]models.MarkType, error)); ok {
		return returnFunc(ctx, lang)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Lang) []models.MarkType); ok {
		r0 = returnFunc(ctx, lang)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.MarkType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Lang) error); ok {
		r1 = returnFunc(ctx, lang)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMarks_GetMarkTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMarkTypes'
type MockMarks_GetMarkTypes_Call struct {
	*mock.Call
}

// GetMarkTypes is a helper method to define mock.On call
//   - ctx context.Context
//   - lang models.Lang
func (_e *MockMarks_Expecter) GetMarkTypes(ctx any, lang any) *MockMarks_GetMarkTypes_Call {
	return &MockMarks_GetMarkTypes_Call{Call: _e.mock.On("GetMarkTypes", ctx, lang)}
}

func (_c *MockMarks_GetMarkTypes_Call) Run(run func(ctx context.Context, lang models.Lang)) *MockMarks_GetMarkTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Lang
		if args[1] != nil {
			arg1 = args[1].(models.Lang)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMarks_GetMarkTypes_Call) Return(markTypes []models.MarkType, err error) *MockMarks_GetMarkTypes_Call {
	_c.Call.Return(markTypes, err)
	return _c
}

func (_c *MockMarks_GetMarkTypes_Call) RunAndReturn(run func(ctx context.Context, lang models.Lang) ([]models.MarkType, error)) *MockMarks_GetMarkTypes_Call {
	_c.Call.Return(run)
	return _c
}

// GetMarksNearby provides a mock function for the type MockMarks
func (_mock *MockMarks) GetMarksNearby(ctx context.Context, filters models.GetMarksNearbyFilters) (models.Page[models.MarkWithDistance], error) {
	ret := _mock.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for GetMarksNearby")
	}

	var r0 models.Page[models.MarkWithDistance]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetMarksNearbyFilters) (models.Page[models.MarkWithDistance], error)); ok {
		return returnFunc(ctx, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetMarksNearbyFilters) models.Page[models.MarkWithDistance]); ok {
		r0 = returnFunc(ctx, filters)
	} else {
		r0 = ret.Get(0).(models.Page[models.MarkWithDistance])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.GetMarksNearbyFilters) error); ok {
		r1 = returnFunc(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMarks_GetMarksNearby_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMarksNearby'
type MockMarks_GetMarksNearby_Call struct {
	*mock.Call
}

// GetMarksNearby is a helper method to define mock.On call
//   - ctx context.Context
//   - filters models.GetMarksNearbyFilters
func (_e *MockMarks_Expecter) GetMarksNearby(ctx any, filters any) *MockMarks_GetMarksNearby_Call {
	return &MockMarks_GetMarksNearby_Call{Call: _e.mock.On("GetMarksNearby", ctx, filters)}
}

func (_c *MockMarks_GetMarksNearby_Call) Run(run func(ctx context.Context, filters models.GetMarksNearbyFilters)) *MockMarks_GetMarksNearby_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.GetMarksNearbyFilters
		if args[1] != nil {
			arg1 = args[1].(models.GetMarksNearbyFilters)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMarks_GetMarksNearby_Call) Return(page models.Page[models.MarkWithDistance], err error) *MockMarks_GetMarksNearby_Call {
	_c.Call.Return(page, err)
	return _c
}

func (_c *MockMarks_GetMarksNearby_Call) RunAndReturn(run func(ctx context.Context, filters models.GetMarksNearbyFilters) (models.Page[models.MarkWithDistance], error)) *MockMarks_GetMarksNearby_Call {
	_c.Call.Return(run)
	return _c
}

// ListFollowedMarks provides a mock function for the type MockMarks
func (_mock *MockMarks) ListFollowedMarks(ctx context.Context, userId int, p models.Pagination) (models.Page[models.Mark], error) {
	ret := _mock.Called(ctx, userId, p)

	if len(ret) == 0 {
		panic("no return value specified for ListFollowedMarks")
	}

	var r0 models.Page[models.Mark]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.Pagination) (models.Page[models.Mark], error)); ok {
		return returnFunc(ctx, userId, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.Pagination) models.Page[models.Mark]); ok {
		r0 = returnFunc(ctx, userId, p)
	} else {
		r0 = ret.Get(0).(models.Page[models.Mark])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, models.Pagination) error); ok {
		r1 = returnFunc(ctx, userId, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMarks_ListFollowedMarks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFollowedMarks'
type MockMarks_ListFollowedMarks_Call struct {
	*mock.Call
}

// ListFollowedMarks is a helper method to define mock.On call
//   - ctx context.Context
//   - userId int
//   - p models.Pagination
func (_e *MockMarks_Expecter) ListFollowedMarks(ctx any, userId any, p any) *MockMarks_ListFollowedMarks_Call {
	return &MockMarks_ListFollowedMarks_Call{Call: _e.mock.On("ListFollowedMarks", ctx, userId, p)}
}

func (_c *MockMarks_ListFollowedMarks_Call) Run(run func(ctx context.Context, userId int, p models.Pagination)) *MockMarks_ListFollowedMarks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 models.Pagination
		if args[2] != nil {
			arg2 = args[2].(models.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMarks_ListFollowedMarks_Call) Return(page models.Page[models.Mark], err error) *MockMarks_ListFollowedMarks_Call {
	_c.Call.Return(page, err)
	return _c
}

func (_c *MockMarks_ListFollowedMarks_Call) RunAndReturn(run func(ctx context.Context, userId int, p models.Pagination) (models.Page[models.Mark], error)) *MockMarks_ListFollowedMarks_Call {
	_c.Call.Return(run)
	return _c
}

// ListMarks provides a mock function for the type MockMarks
func (_mock *MockMarks) ListMarks(ctx context.Context, filters models.GetMarksFilters) (models.Page[models.Mark], error) {
	ret := _mock.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for ListMarks")
	}

	var r0 models.Page[models.Mark]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetMarksFilters) (models.Page[models.Mark], error)); ok {
		return returnFunc(ctx, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetMarksFilters) models.Page[models.Mark]); ok {
		r0 = returnFunc(ctx, filters)
	} else {
		r0 = ret.Get(0).(models.Page[models.Mark])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.GetMarksFilters) error); ok {
		r1 = returnFunc(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMarks_ListMarks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMarks'
type MockMarks_ListMarks_Call struct {
	*mock.Call
}

// ListMarks is a helper method to define mock.On call
//   - ctx context.Context
//   - filters models.GetMarksFilters
func (_e *MockMarks_Expecter) ListMarks(ctx any, filters any) *MockMarks_ListMarks_Call {
	return &MockMarks_ListMarks_Call{Call: _e.mock.On("ListMarks", ctx, filters)}
}

func (_c *MockMarks_ListMarks_Call) Run(run func(ctx context.Context, filters models.GetMarksFilters)) *MockMarks_ListMarks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.GetMarksFilters
		if args[1] != nil {
			arg1 = args[1].(models.GetMarksFilters)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMarks_ListMarks_Call) Return(page models.Page[models.Mark], err error) *MockMarks_ListMarks_Call {
	_c.Call.Return(page, err)
	return _c
}

func (_c *MockMarks_ListMarks_Call) RunAndReturn(run func(ctx context.Context, filters models.GetMarksFilters) (models.Page[models.Mark], error)) *MockMarks_ListMarks_Call {
	_c.Call.Return(run)
	return _c
}

// ListMarksByUserId provides a mock function for the type MockMarks
func (_mock *MockMarks) ListMarksByUserId(ctx context.Context, userId int, p models.Pagination) (models.Page[models.Mark], error) {
	ret := _mock.Called(ctx, userId, p)

	if len(ret) == 0 {
		panic("no return value specified for ListMarksByUserId")
	}

	var r0 models.Page[models.Mark]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.Pagination) (models.Page[models.Mark], error)); ok {
		return returnFunc(ctx, userId, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.Pagination) models.Page[models.Mark]); ok {
		r0 = returnFunc(ctx, userId, p)
	} else {
		r0 = ret.Get(0).(models.Page[models.Mark])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, models.Pagination) error); ok {
		r1 = returnFunc(ctx, userId, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMarks_ListMarksByUserId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMarksByUserId'
type MockMarks_ListMarksByUserId_Call struct {
	*mock.Call
}

// ListMarksByUserId is a helper method to define mock.On call
//   - ctx context.Context
//   - userId int
//   - p models.Pagination
func (_e *MockMarks_Expecter) ListMarksByUserId(ctx any, userId any, p any) *MockMarks_ListMarksByUserId_Call {
	return &MockMarks_ListMarksByUserId_Call{Call: _e.mock.On("ListMarksByUserId", ctx, userId, p)}
}

func (_c *MockMarks_ListMarksByUserId_Call) Run(run func(ctx context.Context, userId int, p models.Pagination)) *MockMarks_ListMarksByUserId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 models.Pagination
		if args[2] != nil {
			arg2 = args[2].(models.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMarks_ListMarksByUserId_Call) Return(page models.Page[models.Mark], err error) *MockMarks_ListMarksByUserId_Call {
	_c.Call.Return(page, err)
	return _c
}

func (_c *MockMarks_ListMarksByUserId_Call) RunAndReturn(run func(ctx context.Context, userId int, p models.Pagination) (models.Page[models.Mark], error)) *MockMarks_ListMarksByUserId_Call {
	_c.Call.Return(run)
	return _c
}

// UnfollowMark provides a mock function for the type MockMarks
func (_mock *MockMarks) UnfollowMark(ctx context.Context, userId int, markId int) error {
	ret := _mock.Called(ctx, userId, markId)

	if len(ret) == 0 {
		panic("no return value specified for UnfollowMark")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = returnFunc(ctx, userId, markId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMarks_UnfollowMark_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnfollowMark'
type MockMarks_UnfollowMark_Call struct {
	*mock.Call
}

// UnfollowMark is a helper method to define mock.On call
//   - ctx context.Context
//   - userId int
//   - markId int
func (_e *MockMarks_Expecter) UnfollowMark(ctx any, userId any, markId any) *MockMarks_UnfollowMark_Call {
	return &MockMarks_UnfollowMark_Call{Call: _e.mock.On("UnfollowMark", ctx, userId, markId)}
}

func (_c *MockMarks_UnfollowMark_Call) Run(run func(ctx context.Context, userId int, markId int)) *MockMarks_UnfollowMark_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMarks_UnfollowMark_Call) Return(err error) *MockMarks_UnfollowMark_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMarks_UnfollowMark_Call) RunAndReturn(run func(ctx context.Context, userId int, markId int) error) *MockMarks_UnfollowMark_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMark provides a mock function for the type MockMarks
func (_mock *MockMarks) UpdateMark(ctx context.Context, actor models.Actor, markId int, upd models.MarkUpdate) (models.Mark, error) {
	ret := _mock.Called(ctx, actor, markId, upd)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMark")
	}

	var r0 models.Mark
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Actor, int, models.MarkUpdate) (models.Mark, error)); ok {
		return returnFunc(ctx, actor, markId, upd)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Actor, int, models.MarkUpdate) models.Mark); ok {
		r0 = returnFunc(ctx, actor, markId, upd)
	} else {
		r0 = ret.Get(0).(models.Mark)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Actor, int, models.MarkUpdate) error); ok {
		r1 = returnFunc(ctx, actor, markId, upd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMarks_UpdateMark_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMark'
type MockMarks_UpdateMark_Call struct {
	*mock.Call
}

// UpdateMark is a helper method to define mock.On call
//   - ctx context.Context
//   - actor models.Actor
//   - markId int
//   - upd models.MarkUpdate
func (_e *MockMarks_Expecter) UpdateMark(ctx any, actor any, markId any, upd any) *MockMarks_UpdateMark_Call {
	return &MockMarks_UpdateMark_Call{Call: _e.mock.On("UpdateMark", ctx, actor, markId, upd)}
}

func (_c *MockMarks_UpdateMark_Call) Run(run func(ctx context.Context, actor models.Actor, markId int, upd models.MarkUpdate)) *MockMarks_UpdateMark_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Actor
		if args[1] != nil {
			arg1 = args[1].(models.Actor)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 models.MarkUpdate
		if args[3] != nil {
			arg3 = args[3].(models.MarkUpdate)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMarks_UpdateMark_Call) Return(mark models.Mark, err error) *MockMarks_UpdateMark_Call {
	_c.Call.Return(mark, err)
	return _c
}

func (_c *MockMarks_UpdateMark_Call) RunAndReturn(run func(ctx context.Context, actor models.Actor, markId int, upd models.MarkUpdate) (models.Mark, error)) *MockMarks_UpdateMark_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStatusUpdater creates a new instance of MockStatusUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStatusUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStatusUpdater {
	mock := &MockStatusUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStatusUpdater is an autogenerated mock type for the StatusUpdater type
type MockStatusUpdater struct {
	mock.Mock
}

type MockStatusUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStatusUpdater) EXPECT() *MockStatusUpdater_Expecter {
	return &MockStatusUpdater_Expecter{mock: &_m.Mock}
}

// Confirm provides a mock function for the type MockStatusUpdater
func (_mock *MockStatusUpdater) Confirm(ctx context.Context, markId int) (models.MarkStatusType, error) {
	ret := _mock.Called(ctx, markId)

	if len(ret) == 0 {
		panic("no return value specified for Confirm")
	}

	var r0 models.MarkStatusType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (models.MarkStatusType, error)); ok {
		return returnFunc(ctx, markId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) models.MarkStatusType); ok {
		r0 = returnFunc(ctx, markId)
	} else {
		r0 = ret.Get(0).(models.MarkStatusType)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, markId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStatusUpdater_Confirm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Confirm'
type MockStatusUpdater_Confirm_Call struct {
	*mock.Call
}

// Confirm is a helper method to define mock.On call
//   - ctx context.Context
//   - markId int
func (_e *MockStatusUpdater_Expecter) Confirm(ctx any, markId any) *MockStatusUpdater_Confirm_Call {
	return &MockStatusUpdater_Confirm_Call{Call: _e.mock.On("Confirm", ctx, markId)}
}

func (_c *MockStatusUpdater_Confirm_Call) Run(run func(ctx context.Context, markId int)) *MockStatusUpdater_Confirm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStatusUpdater_Confirm_Call) Return(markStatusType models.MarkStatusType, err error) *MockStatusUpdater_Confirm_Call {
	_c.Call.Return(markStatusType, err)
	return _c
}

func (_c *MockStatusUpdater_Confirm_Call) RunAndReturn(run func(ctx context.Context, markId int) (models.MarkStatusType, error)) *MockStatusUpdater_Confirm_Call {
	_c.Call.Return(run)
	return _c
}

// Reject provides a mock function for the type MockStatusUpdater
func (_mock *MockStatusUpdater) Reject(ctx context.Context, markId int) (models.MarkStatusType, error) {
	ret := _mock.Called(ctx, markId)

	if len(ret) == 0 {
		panic("no return value specified for Reject")
	}

	var r0 models.MarkStatusType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (models.MarkStatusType, error)); ok {
		return returnFunc(ctx, markId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) models.MarkStatusType); ok {
		r0 = returnFunc(ctx, markId)
	} else {
		r0 = ret.Get(0).(models.MarkStatusType)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, markId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStatusUpdater_Reject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reject'
type MockStatusUpdater_Reject_Call struct {
	*mock.Call
}

// Reject is a helper method to define mock.On call
//   - ctx context.Context
//   - markId int
func (_e *MockStatusUpdater_Expecter) Reject(ctx any, markId any) *MockStatusUpdater_Reject_Call {
	return &MockStatusUpdater_Reject_Call{Call: _e.mock.On("Reject", ctx, markId)}
}

func (_c *MockStatusUpdater_Reject_Call) Run(run func(ctx context.Context, markId int)) *MockStatusUpdater_Reject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStatusUpdater_Reject_Call) Return(markStatusType models.MarkStatusType, err error) *MockStatusUpdater_Reject_Call {
	_c.Call.Return(markStatusType, err)
	return _c
}

func (_c *MockStatusUpdater_Reject_Call) RunAndReturn(run func(ctx context.Context, markId int) (models.MarkStatusType, error)) *MockStatusUpdater_Reject_Call {
	_c.Call.Return(run)
	return _c
}
