// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package marksrest

import (
	"context"
	"io"

	"github.com/PritOriginal/problem-map-server/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMarks creates a new instance of MockMarks. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMarks(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMarks {
	mock := &MockMarks{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMarks is an autogenerated mock type for the Marks type
type MockMarks struct {
	mock.Mock
}

type MockMarks_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMarks) EXPECT() *MockMarks_Expecter {
	return &MockMarks_Expecter{mock: &_m.Mock}
}

// AddMark provides a mock function for the type MockMarks
func (_mock *MockMarks) AddMark(ctx context.Context, mark models.Mark, photos []io.Reader) (int64, error) {
	ret := _mock.Called(ctx, mark, photos)

	if len(ret) == 0 {
		panic("no return value specified for AddMark")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Mark, []io.Reader) (int64, error)); ok {
		return returnFunc(ctx, mark, photos)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Mark, []io.Reader) int64); ok {
		r0 = returnFunc(ctx, mark, photos)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Mark, []io.Reader) error); ok {
		r1 = returnFunc(ctx, mark, photos)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMarks_AddMark_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMark'
type MockMarks_AddMark_Call struct {
	*mock.Call
}

// AddMark is a helper method to define mock.On call
//   - ctx context.Context
//   - mark models.Mark
//   - photos []io.Reader
func (_e *MockMarks_Expecter) AddMark(ctx interface{}, mark interface{}, photos interface{}) *MockMarks_AddMark_Call {
	return &MockMarks_AddMark_Call{Call: _e.mock.On("AddMark", ctx, mark, photos)}
}

func (_c *MockMarks_AddMark_Call) Run(run func(ctx context.Context, mark models.Mark, photos []io.Reader)) *MockMarks_AddMark_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Mark
		if args[1] != nil {
			arg1 = args[1].(models.Mark)
		}
		var arg2 []io.Reader
		if args[2] != nil {
			arg2 = args[2].([]io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMarks_AddMark_Call) Return(n int64, err error) *MockMarks_AddMark_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockMarks_AddMark_Call) RunAndReturn(run func(ctx context.Context, mark models.Mark, photos []io.Reader) (int64, error)) *MockMarks_AddMark_Call {
	_c.Call.Return(run)
	return _c
}

// GetMarkById provides a mock function for the type MockMarks
func (_mock *MockMarks) GetMarkById(ctx context.Context, id int) (models.Mark, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetMarkById")
	}

	var r0 models.Mark
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (models.Mark, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) models.Mark); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Mark)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMarks_GetMarkById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMarkById'
type MockMarks_GetMarkById_Call struct {
	*mock.Call
}

// GetMarkById is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockMarks_Expecter) GetMarkById(ctx interface{}, id interface{}) *MockMarks_GetMarkById_Call {
	return &MockMarks_GetMarkById_Call{Call: _e.mock.On("GetMarkById", ctx, id)}
}

func (_c *MockMarks_GetMarkById_Call) Run(run func(ctx context.Context, id int)) *MockMarks_GetMarkById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMarks_GetMarkById_Call) Return(mark models.Mark, err error) *MockMarks_GetMarkById_Call {
	_c.Call.Return(mark, err)
	return _c
}

func (_c *MockMarks_GetMarkById_Call) RunAndReturn(run func(ctx context.Context, id int) (models.Mark, error)) *MockMarks_GetMarkById_Call {
	_c.Call.Return(run)
	return _c
}

// GetMarkStatuses provides a mock function for the type MockMarks
func (_mock *MockMarks) GetMarkStatuses(ctx context.Context) ([]models.MarkStatus, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMarkStatuses")
	}

	var r0 []models.MarkStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.MarkStatus, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.MarkStatus); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.MarkStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMarks_GetMarkStatuses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMarkStatuses'
type MockMarks_GetMarkStatuses_Call struct {
	*mock.Call
}

// GetMarkStatuses is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMarks_Expecter) GetMarkStatuses(ctx interface{}) *MockMarks_GetMarkStatuses_Call {
	return &MockMarks_GetMarkStatuses_Call{Call: _e.mock.On("GetMarkStatuses", ctx)}
}

func (_c *MockMarks_GetMarkStatuses_Call) Run(run func(ctx context.Context)) *MockMarks_GetMarkStatuses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMarks_GetMarkStatuses_Call) Return(markStatuss []models.MarkStatus, err error) *MockMarks_GetMarkStatuses_Call {
	_c.Call.Return(markStatuss, err)
	return _c
}

func (_c *MockMarks_GetMarkStatuses_Call) RunAndReturn(run func(ctx context.Context) ([]models.MarkStatus, error)) *MockMarks_GetMarkStatuses_Call {
	_c.Call.Return(run)
	return _c
}

// GetMarkTypes provides a mock function for the type MockMarks
func (_mock *MockMarks) GetMarkTypes(ctx context.Context) ([]models.MarkType, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMarkTypes")
	}

	var r0 []models.MarkType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.MarkType, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.MarkType); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.MarkType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMarks_GetMarkTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMarkTypes'
type MockMarks_GetMarkTypes_Call struct {
	*mock.Call
}

// GetMarkTypes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMarks_Expecter) GetMarkTypes(ctx interface{}) *MockMarks_GetMarkTypes_Call {
	return &MockMarks_GetMarkTypes_Call{Call: _e.mock.On("GetMarkTypes", ctx)}
}

func (_c *MockMarks_GetMarkTypes_Call) Run(run func(ctx context.Context)) *MockMarks_GetMarkTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMarks_GetMarkTypes_Call) Return(markTypes []models.MarkType, err error) *MockMarks_GetMarkTypes_Call {
	_c.Call.Return(markTypes, err)
	return _c
}

func (_c *MockMarks_GetMarkTypes_Call) RunAndReturn(run func(ctx context.Context) ([]models.MarkType, error)) *MockMarks_GetMarkTypes_Call {
	_c.Call.Return(run)
	return _c
}

// GetMarks provides a mock function for the type MockMarks
func (_mock *MockMarks) GetMarks(ctx context.Context) ([]models.Mark, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMarks")
	}

	var r0 []models.Mark
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.Mark, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.Mark); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Mark)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMarks_GetMarks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMarks'
type MockMarks_GetMarks_Call struct {
	*mock.Call
}

// GetMarks is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMarks_Expecter) GetMarks(ctx interface{}) *MockMarks_GetMarks_Call {
	return &MockMarks_GetMarks_Call{Call: _e.mock.On("GetMarks", ctx)}
}

func (_c *MockMarks_GetMarks_Call) Run(run func(ctx context.Context)) *MockMarks_GetMarks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMarks_GetMarks_Call) Return(marks []models.Mark, err error) *MockMarks_GetMarks_Call {
	_c.Call.Return(marks, err)
	return _c
}

func (_c *MockMarks_GetMarks_Call) RunAndReturn(run func(ctx context.Context) ([]models.Mark, error)) *MockMarks_GetMarks_Call {
	_c.Call.Return(run)
	return _c
}

// GetMarksByUserId provides a mock function for the type MockMarks
func (_mock *MockMarks) GetMarksByUserId(ctx context.Context, userId int) ([]models.Mark, error) {
	ret := _mock.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetMarksByUserId")
	}

	var r0 []models.Mark
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]models.Mark, error)); ok {
		return returnFunc(ctx, userId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []models.Mark); ok {
		r0 = returnFunc(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Mark)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMarks_GetMarksByUserId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMarksByUserId'
type MockMarks_GetMarksByUserId_Call struct {
	*mock.Call
}

// GetMarksByUserId is a helper method to define mock.On call
//   - ctx context.Context
//   - userId int
func (_e *MockMarks_Expecter) GetMarksByUserId(ctx interface{}, userId interface{}) *MockMarks_GetMarksByUserId_Call {
	return &MockMarks_GetMarksByUserId_Call{Call: _e.mock.On("GetMarksByUserId", ctx, userId)}
}

func (_c *MockMarks_GetMarksByUserId_Call) Run(run func(ctx context.Context, userId int)) *MockMarks_GetMarksByUserId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMarks_GetMarksByUserId_Call) Return(marks []models.Mark, err error) *MockMarks_GetMarksByUserId_Call {
	_c.Call.Return(marks, err)
	return _c
}

func (_c *MockMarks_GetMarksByUserId_Call) RunAndReturn(run func(ctx context.Context, userId int) ([]models.Mark, error)) *MockMarks_GetMarksByUserId_Call {
	_c.Call.Return(run)
	return _c
}
