// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package checksrest

import (
	"context"

	"github.com/PritOriginal/problem-map-server/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockChecks creates a new instance of MockChecks. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChecks(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChecks {
	mock := &MockChecks{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChecks is an autogenerated mock type for the Checks type
type MockChecks struct {
	mock.Mock
}

type MockChecks_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChecks) EXPECT() *MockChecks_Expecter {
	return &MockChecks_Expecter{mock: &_m.Mock}
}

// AddCheck provides a mock function for the type MockChecks
func (_mock *MockChecks) AddCheck(ctx context.Context, check models.Check, photos [][]byte) (int64, error) {
	ret := _mock.Called(ctx, check, photos)

	if len(ret) == 0 {
		panic("no return value specified for AddCheck")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Check, [][]byte) (int64, error)); ok {
		return returnFunc(ctx, check, photos)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Check, [][]byte) int64); ok {
		r0 = returnFunc(ctx, check, photos)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Check, [][]byte) error); ok {
		r1 = returnFunc(ctx, check, photos)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChecks_AddCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddCheck'
type MockChecks_AddCheck_Call struct {
	*mock.Call
}

// AddCheck is a helper method to define mock.On call
//   - ctx context.Context
//   - check models.Check
//   - photos [][]byte
func (_e *MockChecks_Expecter) AddCheck(ctx interface{}, check interface{}, photos interface{}) *MockChecks_AddCheck_Call {
	return &MockChecks_AddCheck_Call{Call: _e.mock.On("AddCheck", ctx, check, photos)}
}

func (_c *MockChecks_AddCheck_Call) Run(run func(ctx context.Context, check models.Check, photos [][]byte)) *MockChecks_AddCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Check
		if args[1] != nil {
			arg1 = args[1].(models.Check)
		}
		var arg2 [][]byte
		if args[2] != nil {
			arg2 = args[2].([][]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockChecks_AddCheck_Call) Return(n int64, err error) *MockChecks_AddCheck_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockChecks_AddCheck_Call) RunAndReturn(run func(ctx context.Context, check models.Check, photos [][]byte) (int64, error)) *MockChecks_AddCheck_Call {
	_c.Call.Return(run)
	return _c
}

// GetCheckById provides a mock function for the type MockChecks
func (_mock *MockChecks) GetCheckById(ctx context.Context, id int) (models.Check, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCheckById")
	}

	var r0 models.Check
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (models.Check, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) models.Check); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Check)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChecks_GetCheckById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCheckById'
type MockChecks_GetCheckById_Call struct {
	*mock.Call
}

// GetCheckById is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockChecks_Expecter) GetCheckById(ctx interface{}, id interface{}) *MockChecks_GetCheckById_Call {
	return &MockChecks_GetCheckById_Call{Call: _e.mock.On("GetCheckById", ctx, id)}
}

func (_c *MockChecks_GetCheckById_Call) Run(run func(ctx context.Context, id int)) *MockChecks_GetCheckById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChecks_GetCheckById_Call) Return(check models.Check, err error) *MockChecks_GetCheckById_Call {
	_c.Call.Return(check, err)
	return _c
}

func (_c *MockChecks_GetCheckById_Call) RunAndReturn(run func(ctx context.Context, id int) (models.Check, error)) *MockChecks_GetCheckById_Call {
	_c.Call.Return(run)
	return _c
}

// GetChecksByMarkId provides a mock function for the type MockChecks
func (_mock *MockChecks) GetChecksByMarkId(ctx context.Context, markId int) ([]models.Check, error) {
	ret := _mock.Called(ctx, markId)

	if len(ret) == 0 {
		panic("no return value specified for GetChecksByMarkId")
	}

	var r0 []models.Check
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]models.Check, error)); ok {
		return returnFunc(ctx, markId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []models.Check); ok {
		r0 = returnFunc(ctx, markId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Check)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, markId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChecks_GetChecksByMarkId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChecksByMarkId'
type MockChecks_GetChecksByMarkId_Call struct {
	*mock.Call
}

// GetChecksByMarkId is a helper method to define mock.On call
//   - ctx context.Context
//   - markId int
func (_e *MockChecks_Expecter) GetChecksByMarkId(ctx interface{}, markId interface{}) *MockChecks_GetChecksByMarkId_Call {
	return &MockChecks_GetChecksByMarkId_Call{Call: _e.mock.On("GetChecksByMarkId", ctx, markId)}
}

func (_c *MockChecks_GetChecksByMarkId_Call) Run(run func(ctx context.Context, markId int)) *MockChecks_GetChecksByMarkId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChecks_GetChecksByMarkId_Call) Return(checks []models.Check, err error) *MockChecks_GetChecksByMarkId_Call {
	_c.Call.Return(checks, err)
	return _c
}

func (_c *MockChecks_GetChecksByMarkId_Call) RunAndReturn(run func(ctx context.Context, markId int) ([]models.Check, error)) *MockChecks_GetChecksByMarkId_Call {
	_c.Call.Return(run)
	return _c
}

// GetChecksByUserId provides a mock function for the type MockChecks
func (_mock *MockChecks) GetChecksByUserId(ctx context.Context, userId int) ([]models.Check, error) {
	ret := _mock.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetChecksByUserId")
	}

	var r0 []models.Check
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]models.Check, error)); ok {
		return returnFunc(ctx, userId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []models.Check); ok {
		r0 = returnFunc(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Check)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChecks_GetChecksByUserId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChecksByUserId'
type MockChecks_GetChecksByUserId_Call struct {
	*mock.Call
}

// GetChecksByUserId is a helper method to define mock.On call
//   - ctx context.Context
//   - userId int
func (_e *MockChecks_Expecter) GetChecksByUserId(ctx interface{}, userId interface{}) *MockChecks_GetChecksByUserId_Call {
	return &MockChecks_GetChecksByUserId_Call{Call: _e.mock.On("GetChecksByUserId", ctx, userId)}
}

func (_c *MockChecks_GetChecksByUserId_Call) Run(run func(ctx context.Context, userId int)) *MockChecks_GetChecksByUserId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChecks_GetChecksByUserId_Call) Return(checks []models.Check, err error) *MockChecks_GetChecksByUserId_Call {
	_c.Call.Return(checks, err)
	return _c
}

func (_c *MockChecks_GetChecksByUserId_Call) RunAndReturn(run func(ctx context.Context, userId int) ([]models.Check, error)) *MockChecks_GetChecksByUserId_Call {
	_c.Call.Return(run)
	return _c
}
