// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package checksrest

import (
	"context"
	"io"

	"github.com/PritOriginal/problem-map-server/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockChecks creates a new instance of MockChecks. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChecks(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChecks {
	mock := &MockChecks{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChecks is an autogenerated mock type for the Checks type
type MockChecks struct {
	mock.Mock
}

type MockChecks_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChecks) EXPECT() *MockChecks_Expecter {
	return &MockChecks_Expecter{mock: &_m.Mock}
}

// AddCheck provides a mock function for the type MockChecks
func (_mock *MockChecks) AddCheck(ctx context.Context, check models.Check, photos []io.Reader) (int64, error) {
	ret := _mock.Called(ctx, check, photos)

	if len(ret) == 0 {
		panic("no return value specified for AddCheck")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Check, []io.Reader) (int64, error)); ok {
		return returnFunc(ctx, check, photos)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Check, []io.Reader) int64); ok {
		r0 = returnFunc(ctx, check, photos)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Check, []io.Reader) error); ok {
		r1 = returnFunc(ctx, check, photos)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChecks_AddCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddCheck'
type MockChecks_AddCheck_Call struct {
	*mock.Call
}

// AddCheck is a helper method to define mock.On call
//   - ctx context.Context
//   - check models.Check
//   - photos []io.Reader
func (_e *MockChecks_Expecter) AddCheck(ctx any, check any, photos any) *MockChecks_AddCheck_Call {
	return &MockChecks_AddCheck_Call{Call: _e.mock.On("AddCheck", ctx, check, photos)}
}

func (_c *MockChecks_AddCheck_Call) Run(run func(ctx context.Context, check models.Check, photos []io.Reader)) *MockChecks_AddCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Check
		if args[1] != nil {
			arg1 = args[1].(models.Check)
		}
		var arg2 []io.Reader
		if args[2] != nil {
			arg2 = args[2].([]io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockChecks_AddCheck_Call) Return(n int64, err error) *MockChecks_AddCheck_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockChecks_AddCheck_Call) RunAndReturn(run func(ctx context.Context, check models.Check, photos []io.Reader) (int64, error)) *MockChecks_AddCheck_Call {
	_c.Call.Return(run)
	return _c
}

// GetCheckById provides a mock function for the type MockChecks
func (_mock *MockChecks) GetCheckById(ctx context.Context, id int) (models.Check, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCheckById")
	}

	var r0 models.Check
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (models.Check, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) models.Check); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Check)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChecks_GetCheckById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCheckById'
type MockChecks_GetCheckById_Call struct {
	*mock.Call
}

// GetCheckById is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockChecks_Expecter) GetCheckById(ctx any, id any) *MockChecks_GetCheckById_Call {
	return &MockChecks_GetCheckById_Call{Call: _e.mock.On("GetCheckById", ctx, id)}
}

func (_c *MockChecks_GetCheckById_Call) Run(run func(ctx context.Context, id int)) *MockChecks_GetCheckById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChecks_GetCheckById_Call) Return(check models.Check, err error) *MockChecks_GetCheckById_Call {
	_c.Call.Return(check, err)
	return _c
}

func (_c *MockChecks_GetCheckById_Call) RunAndReturn(run func(ctx context.Context, id int) (models.Check, error)) *MockChecks_GetCheckById_Call {
	_c.Call.Return(run)
	return _c
}

// ListChecksByMarkId provides a mock function for the type MockChecks
func (_mock *MockChecks) ListChecksByMarkId(ctx context.Context, markId int, p models.Pagination) (models.Page[models.Check], error) {
	ret := _mock.Called(ctx, markId, p)

	if len(ret) == 0 {
		panic("no return value specified for ListChecksByMarkId")
	}

	var r0 models.Page[models.Check]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.Pagination) (models.Page[models.Check], error)); ok {
		return returnFunc(ctx, markId, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.Pagination) models.Page[models.Check]); ok {
		r0 = returnFunc(ctx, markId, p)
	} else {
		r0 = ret.Get(0).(models.Page[models.Check])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, models.Pagination) error); ok {
		r1 = returnFunc(ctx, markId, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChecks_ListChecksByMarkId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListChecksByMarkId'
type MockChecks_ListChecksByMarkId_Call struct {
	*mock.Call
}

// ListChecksByMarkId is a helper method to define mock.On call
//   - ctx context.Context
//   - markId int
//   - p models.Pagination
func (_e *MockChecks_Expecter) ListChecksByMarkId(ctx any, markId any, p any) *MockChecks_ListChecksByMarkId_Call {
	return &MockChecks_ListChecksByMarkId_Call{Call: _e.mock.On("ListChecksByMarkId", ctx, markId, p)}
}

func (_c *MockChecks_ListChecksByMarkId_Call) Run(run func(ctx context.Context, markId int, p models.Pagination)) *MockChecks_ListChecksByMarkId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 models.Pagination
		if args[2] != nil {
			arg2 = args[2].(models.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockChecks_ListChecksByMarkId_Call) Return(page models.Page[models.Check], err error) *MockChecks_ListChecksByMarkId_Call {
	_c.Call.Return(page, err)
	return _c
}

func (_c *MockChecks_ListChecksByMarkId_Call) RunAndReturn(run func(ctx context.Context, markId int, p models.Pagination) (models.Page[models.Check], error)) *MockChecks_ListChecksByMarkId_Call {
	_c.Call.Return(run)
	return _c
}

// ListChecksByUserId provides a mock function for the type MockChecks
func (_mock *MockChecks) ListChecksByUserId(ctx context.Context, userId int, p models.Pagination) (models.Page[models.Check], error) {
	ret := _mock.Called(ctx, userId, p)

	if len(ret) == 0 {
		panic("no return value specified for ListChecksByUserId")
	}

	var r0 models.Page[models.Check]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.Pagination) (models.Page[models.Check], error)); ok {
		return returnFunc(ctx, userId, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.Pagination) models.Page[models.Check]); ok {
		r0 = returnFunc(ctx, userId, p)
	} else {
		r0 = ret.Get(0).(models.Page[models.Check])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, models.Pagination) error); ok {
		r1 = returnFunc(ctx, userId, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChecks_ListChecksByUserId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListChecksByUserId'
type MockChecks_ListChecksByUserId_Call struct {
	*mock.Call
}

// ListChecksByUserId is a helper method to define mock.On call
//   - ctx context.Context
//   - userId int
//   - p models.Pagination
func (_e *MockChecks_Expecter) ListChecksByUserId(ctx any, userId any, p any) *MockChecks_ListChecksByUserId_Call {
	return &MockChecks_ListChecksByUserId_Call{Call: _e.mock.On("ListChecksByUserId", ctx, userId, p)}
}

func (_c *MockChecks_ListChecksByUserId_Call) Run(run func(ctx context.Context, userId int, p models.Pagination)) *MockChecks_ListChecksByUserId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 models.Pagination
		if args[2] != nil {
			arg2 = args[2].(models.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockChecks_ListChecksByUserId_Call) Return(page models.Page[models.Check], err error) *MockChecks_ListChecksByUserId_Call {
	_c.Call.Return(page, err)
	return _c
}

func (_c *MockChecks_ListChecksByUserId_Call) RunAndReturn(run func(ctx context.Context, userId int, p models.Pagination) (models.Page[models.Check], error)) *MockChecks_ListChecksByUserId_Call {
	_c.Call.Return(run)
	return _c
}
