// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package idempotency

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// Del provides a mock function for the type MockStore
func (_mock *MockStore) Del(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Del")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_Del_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Del'
type MockStore_Del_Call struct {
	*mock.Call
}

// Del is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockStore_Expecter) Del(ctx any, key any) *MockStore_Del_Call {
	return &MockStore_Del_Call{Call: _e.mock.On("Del", ctx, key)}
}

func (_c *MockStore_Del_Call) Run(run func(ctx context.Context, key string)) *MockStore_Del_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_Del_Call) Return(err error) *MockStore_Del_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_Del_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockStore_Del_Call {
	_c.Call.Return(run)
	return _c
}

// GetBytes provides a mock function for the type MockStore
func (_mock *MockStore) GetBytes(ctx context.Context, key string) ([]byte, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetBytes")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBytes'
type MockStore_GetBytes_Call struct {
	*mock.Call
}

// GetBytes is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockStore_Expecter) GetBytes(ctx any, key any) *MockStore_GetBytes_Call {
	return &MockStore_GetBytes_Call{Call: _e.mock.On("GetBytes", ctx, key)}
}

func (_c *MockStore_GetBytes_Call) Run(run func(ctx context.Context, key string)) *MockStore_GetBytes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetBytes_Call) Return(bytes []byte, err error) *MockStore_GetBytes_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockStore_GetBytes_Call) RunAndReturn(run func(ctx context.Context, key string) ([]byte, error)) *MockStore_GetBytes_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockStore
func (_mock *MockStore) Set(ctx context.Context, key string, value any, expiration time.Duration) error {
	ret := _mock.Called(ctx, key, value, expiration)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, time.Duration) error); ok {
		r0 = returnFunc(ctx, key, value, expiration)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockStore_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value any
//   - expiration time.Duration
func (_e *MockStore_Expecter) Set(ctx any, key any, value any, expiration any) *MockStore_Set_Call {
	return &MockStore_Set_Call{Call: _e.mock.On("Set", ctx, key, value, expiration)}
}

func (_c *MockStore_Set_Call) Run(run func(ctx context.Context, key string, value any, expiration time.Duration)) *MockStore_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStore_Set_Call) Return(err error) *MockStore_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_Set_Call) RunAndReturn(run func(ctx context.Context, key string, value any, expiration time.Duration) error) *MockStore_Set_Call {
	_c.Call.Return(run)
	return _c
}

// SetNX provides a mock function for the type MockStore
func (_mock *MockStore) SetNX(ctx context.Context, key string, value any, expiration time.Duration) (bool, error) {
	ret := _mock.Called(ctx, key, value, expiration)

	if len(ret) == 0 {
		panic("no return value specified for SetNX")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, time.Duration) (bool, error)); ok {
		return returnFunc(ctx, key, value, expiration)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, time.Duration) bool); ok {
		r0 = returnFunc(ctx, key, value, expiration)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, any, time.Duration) error); ok {
		r1 = returnFunc(ctx, key, value, expiration)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_SetNX_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNX'
type MockStore_SetNX_Call struct {
	*mock.Call
}

// SetNX is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value any
//   - expiration time.Duration
func (_e *MockStore_Expecter) SetNX(ctx any, key any, value any, expiration any) *MockStore_SetNX_Call {
	return &MockStore_SetNX_Call{Call: _e.mock.On("SetNX", ctx, key, value, expiration)}
}

func (_c *MockStore_SetNX_Call) Run(run func(ctx context.Context, key string, value any, expiration time.Duration)) *MockStore_SetNX_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStore_SetNX_Call) Return(b bool, err error) *MockStore_SetNX_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockStore_SetNX_Call) RunAndReturn(run func(ctx context.Context, key string, value any, expiration time.Duration) (bool, error)) *MockStore_SetNX_Call {
	_c.Call.Return(run)
	return _c
}
