// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package adminrest

import (
	"context"

	"github.com/PritOriginal/problem-map-server/internal/models"
	"github.com/PritOriginal/problem-map-server/internal/usecase"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSettings creates a new instance of MockSettings. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSettings(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSettings {
	mock := &MockSettings{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSettings is an autogenerated mock type for the Settings type
type MockSettings struct {
	mock.Mock
}

type MockSettings_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSettings) EXPECT() *MockSettings_Expecter {
	return &MockSettings_Expecter{mock: &_m.Mock}
}

// History provides a mock function for the type MockSettings
func (_mock *MockSettings) History(ctx context.Context, limit int) ([]models.SettingChange, error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for History")
	}

	var r0 []models.SettingChange
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]models.SettingChange, error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []models.SettingChange); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.SettingChange)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSettings_History_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'History'
type MockSettings_History_Call struct {
	*mock.Call
}

// History is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockSettings_Expecter) History(ctx any, limit any) *MockSettings_History_Call {
	return &MockSettings_History_Call{Call: _e.mock.On("History", ctx, limit)}
}

func (_c *MockSettings_History_Call) Run(run func(ctx context.Context, limit int)) *MockSettings_History_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSettings_History_Call) Return(settingChanges []models.SettingChange, err error) *MockSettings_History_Call {
	_c.Call.Return(settingChanges, err)
	return _c
}

func (_c *MockSettings_History_Call) RunAndReturn(run func(ctx context.Context, limit int) ([]models.SettingChange, error)) *MockSettings_History_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function for the type MockSettings
func (_mock *MockSettings) Load(ctx context.Context) (usecase.RuntimeSettings, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 usecase.RuntimeSettings
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (usecase.RuntimeSettings, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) usecase.RuntimeSettings); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(usecase.RuntimeSettings)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSettings_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockSettings_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSettings_Expecter) Load(ctx any) *MockSettings_Load_Call {
	return &MockSettings_Load_Call{Call: _e.mock.On("Load", ctx)}
}

func (_c *MockSettings_Load_Call) Run(run func(ctx context.Context)) *MockSettings_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSettings_Load_Call) Return(runtimeSettings usecase.RuntimeSettings, err error) *MockSettings_Load_Call {
	_c.Call.Return(runtimeSettings, err)
	return _c
}

func (_c *MockSettings_Load_Call) RunAndReturn(run func(ctx context.Context) (usecase.RuntimeSettings, error)) *MockSettings_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockSettings
func (_mock *MockSettings) Update(ctx context.Context, s usecase.RuntimeSettings, updatedBy int) (usecase.RuntimeSettings, error) {
	ret := _mock.Called(ctx, s, updatedBy)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 usecase.RuntimeSettings
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.RuntimeSettings, int) (usecase.RuntimeSettings, error)); ok {
		return returnFunc(ctx, s, updatedBy)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.RuntimeSettings, int) usecase.RuntimeSettings); ok {
		r0 = returnFunc(ctx, s, updatedBy)
	} else {
		r0 = ret.Get(0).(usecase.RuntimeSettings)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, usecase.RuntimeSettings, int) error); ok {
		r1 = returnFunc(ctx, s, updatedBy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSettings_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSettings_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - s usecase.RuntimeSettings
//   - updatedBy int
func (_e *MockSettings_Expecter) Update(ctx any, s any, updatedBy any) *MockSettings_Update_Call {
	return &MockSettings_Update_Call{Call: _e.mock.On("Update", ctx, s, updatedBy)}
}

func (_c *MockSettings_Update_Call) Run(run func(ctx context.Context, s usecase.RuntimeSettings, updatedBy int)) *MockSettings_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 usecase.RuntimeSettings
		if args[1] != nil {
			arg1 = args[1].(usecase.RuntimeSettings)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSettings_Update_Call) Return(runtimeSettings usecase.RuntimeSettings, err error) *MockSettings_Update_Call {
	_c.Call.Return(runtimeSettings, err)
	return _c
}

func (_c *MockSettings_Update_Call) RunAndReturn(run func(ctx context.Context, s usecase.RuntimeSettings, updatedBy int) (usecase.RuntimeSettings, error)) *MockSettings_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMarkTypes creates a new instance of MockMarkTypes. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMarkTypes(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMarkTypes {
	mock := &MockMarkTypes{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMarkTypes is an autogenerated mock type for the MarkTypes type
type MockMarkTypes struct {
	mock.Mock
}

type MockMarkTypes_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMarkTypes) EXPECT() *MockMarkTypes_Expecter {
	return &MockMarkTypes_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockMarkTypes
func (_mock *MockMarkTypes) Create(ctx context.Context, t models.MarkTypeCreate, lang models.Lang) (models.MarkType, error) {
	ret := _mock.Called(ctx, t, lang)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.MarkType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.MarkTypeCreate, models.Lang) (models.MarkType, error)); ok {
		return returnFunc(ctx, t, lang)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.MarkTypeCreate, models.Lang) models.MarkType); ok {
		r0 = returnFunc(ctx, t, lang)
	} else {
		r0 = ret.Get(0).(models.MarkType)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.MarkTypeCreate, models.Lang) error); ok {
		r1 = returnFunc(ctx, t, lang)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMarkTypes_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockMarkTypes_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - t models.MarkTypeCreate
//   - lang models.Lang
func (_e *MockMarkTypes_Expecter) Create(ctx any, t any, lang any) *MockMarkTypes_Create_Call {
	return &MockMarkTypes_Create_Call{Call: _e.mock.On("Create", ctx, t, lang)}
}

func (_c *MockMarkTypes_Create_Call) Run(run func(ctx context.Context, t models.MarkTypeCreate, lang models.Lang)) *MockMarkTypes_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.MarkTypeCreate
		if args[1] != nil {
			arg1 = args[1].(models.MarkTypeCreate)
		}
		var arg2 models.Lang
		if args[2] != nil {
			arg2 = args[2].(models.Lang)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMarkTypes_Create_Call) Return(markType models.MarkType, err error) *MockMarkTypes_Create_Call {
	_c.Call.Return(markType, err)
	return _c
}

func (_c *MockMarkTypes_Create_Call) RunAndReturn(run func(ctx context.Context, t models.MarkTypeCreate, lang models.Lang) (models.MarkType, error)) *MockMarkTypes_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockMarkTypes
func (_mock *MockMarkTypes) List(ctx context.Context, lang models.Lang) ([]models.MarkType, error) {
	ret := _mock.Called(ctx, lang)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.MarkType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Lang) ([]models.MarkType, error)); ok {
		return returnFunc(ctx, lang)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Lang) []models.MarkType); ok {
		r0 = returnFunc(ctx, lang)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.MarkType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Lang) error); ok {
		r1 = returnFunc(ctx, lang)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMarkTypes_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockMarkTypes_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - lang models.Lang
func (_e *MockMarkTypes_Expecter) List(ctx any, lang any) *MockMarkTypes_List_Call {
	return &MockMarkTypes_List_Call{Call: _e.mock.On("List", ctx, lang)}
}

func (_c *MockMarkTypes_List_Call) Run(run func(ctx context.Context, lang models.Lang)) *MockMarkTypes_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Lang
		if args[1] != nil {
			arg1 = args[1].(models.Lang)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMarkTypes_List_Call) Return(markTypes []models.MarkType, err error) *MockMarkTypes_List_Call {
	_c.Call.Return(markTypes, err)
	return _c
}

func (_c *MockMarkTypes_List_Call) RunAndReturn(run func(ctx context.Context, lang models.Lang) ([]models.MarkType, error)) *MockMarkTypes_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockMarkTypes
func (_mock *MockMarkTypes) Update(ctx context.Context, id int, upd models.MarkTypeUpdate, lang models.Lang) (models.MarkType, error) {
	ret := _mock.Called(ctx, id, upd, lang)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 models.MarkType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.MarkTypeUpdate, models.Lang) (models.MarkType, error)); ok {
		return returnFunc(ctx, id, upd, lang)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.MarkTypeUpdate, models.Lang) models.MarkType); ok {
		r0 = returnFunc(ctx, id, upd, lang)
	} else {
		r0 = ret.Get(0).(models.MarkType)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, models.MarkTypeUpdate, models.Lang) error); ok {
		r1 = returnFunc(ctx, id, upd, lang)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMarkTypes_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockMarkTypes_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - upd models.MarkTypeUpdate
//   - lang models.Lang
func (_e *MockMarkTypes_Expecter) Update(ctx any, id any, upd any, lang any) *MockMarkTypes_Update_Call {
	return &MockMarkTypes_Update_Call{Call: _e.mock.On("Update", ctx, id, upd, lang)}
}

func (_c *MockMarkTypes_Update_Call) Run(run func(ctx context.Context, id int, upd models.MarkTypeUpdate, lang models.Lang)) *MockMarkTypes_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 models.MarkTypeUpdate
		if args[2] != nil {
			arg2 = args[2].(models.MarkTypeUpdate)
		}
		var arg3 models.Lang
		if args[3] != nil {
			arg3 = args[3].(models.Lang)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMarkTypes_Update_Call) Return(markType models.MarkType, err error) *MockMarkTypes_Update_Call {
	_c.Call.Return(markType, err)
	return _c
}

func (_c *MockMarkTypes_Update_Call) RunAndReturn(run func(ctx context.Context, id int, upd models.MarkTypeUpdate, lang models.Lang) (models.MarkType, error)) *MockMarkTypes_Update_Call {
	_c.Call.Return(run)
	return _c
}
