// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package maprest

import (
	"context"

	"github.com/PritOriginal/problem-map-server/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMap creates a new instance of MockMap. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMap(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMap {
	mock := &MockMap{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMap is an autogenerated mock type for the Map type
type MockMap struct {
	mock.Mock
}

type MockMap_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMap) EXPECT() *MockMap_Expecter {
	return &MockMap_Expecter{mock: &_m.Mock}
}

// GetCities provides a mock function for the type MockMap
func (_mock *MockMap) GetCities(ctx context.Context) ([]models.City, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetCities")
	}

	var r0 []models.City
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.City, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.City); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.City)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMap_GetCities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCities'
type MockMap_GetCities_Call struct {
	*mock.Call
}

// GetCities is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMap_Expecter) GetCities(ctx interface{}) *MockMap_GetCities_Call {
	return &MockMap_GetCities_Call{Call: _e.mock.On("GetCities", ctx)}
}

func (_c *MockMap_GetCities_Call) Run(run func(ctx context.Context)) *MockMap_GetCities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMap_GetCities_Call) Return(citys []models.City, err error) *MockMap_GetCities_Call {
	_c.Call.Return(citys, err)
	return _c
}

func (_c *MockMap_GetCities_Call) RunAndReturn(run func(ctx context.Context) ([]models.City, error)) *MockMap_GetCities_Call {
	_c.Call.Return(run)
	return _c
}

// GetDistricts provides a mock function for the type MockMap
func (_mock *MockMap) GetDistricts(ctx context.Context) ([]models.District, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDistricts")
	}

	var r0 []models.District
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.District, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.District); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.District)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMap_GetDistricts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDistricts'
type MockMap_GetDistricts_Call struct {
	*mock.Call
}

// GetDistricts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMap_Expecter) GetDistricts(ctx interface{}) *MockMap_GetDistricts_Call {
	return &MockMap_GetDistricts_Call{Call: _e.mock.On("GetDistricts", ctx)}
}

func (_c *MockMap_GetDistricts_Call) Run(run func(ctx context.Context)) *MockMap_GetDistricts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMap_GetDistricts_Call) Return(districts []models.District, err error) *MockMap_GetDistricts_Call {
	_c.Call.Return(districts, err)
	return _c
}

func (_c *MockMap_GetDistricts_Call) RunAndReturn(run func(ctx context.Context) ([]models.District, error)) *MockMap_GetDistricts_Call {
	_c.Call.Return(run)
	return _c
}

// GetRegions provides a mock function for the type MockMap
func (_mock *MockMap) GetRegions(ctx context.Context) ([]models.Region, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRegions")
	}

	var r0 []models.Region
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.Region, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.Region); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Region)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMap_GetRegions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRegions'
type MockMap_GetRegions_Call struct {
	*mock.Call
}

// GetRegions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMap_Expecter) GetRegions(ctx interface{}) *MockMap_GetRegions_Call {
	return &MockMap_GetRegions_Call{Call: _e.mock.On("GetRegions", ctx)}
}

func (_c *MockMap_GetRegions_Call) Run(run func(ctx context.Context)) *MockMap_GetRegions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMap_GetRegions_Call) Return(regions []models.Region, err error) *MockMap_GetRegions_Call {
	_c.Call.Return(regions, err)
	return _c
}

func (_c *MockMap_GetRegions_Call) RunAndReturn(run func(ctx context.Context) ([]models.Region, error)) *MockMap_GetRegions_Call {
	_c.Call.Return(run)
	return _c
}
