// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package maprest

import (
	"context"

	"github.com/PritOriginal/problem-map-server/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMap creates a new instance of MockMap. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMap(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMap {
	mock := &MockMap{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMap is an autogenerated mock type for the Map type
type MockMap struct {
	mock.Mock
}

type MockMap_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMap) EXPECT() *MockMap_Expecter {
	return &MockMap_Expecter{mock: &_m.Mock}
}

// GetAdminBoundaries provides a mock function for the type MockMap
func (_mock *MockMap) GetAdminBoundaries(ctx context.Context, filters models.GetAdminBoundaryFilters) ([]models.AdminBoundary, error) {
	ret := _mock.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for GetAdminBoundaries")
	}

	var r0 []models.AdminBoundary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetAdminBoundaryFilters) ([]models.AdminBoundary, error)); ok {
		return returnFunc(ctx, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetAdminBoundaryFilters) []models.AdminBoundary); ok {
		r0 = returnFunc(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.AdminBoundary)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.GetAdminBoundaryFilters) error); ok {
		r1 = returnFunc(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMap_GetAdminBoundaries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAdminBoundaries'
type MockMap_GetAdminBoundaries_Call struct {
	*mock.Call
}

// GetAdminBoundaries is a helper method to define mock.On call
//   - ctx context.Context
//   - filters models.GetAdminBoundaryFilters
func (_e *MockMap_Expecter) GetAdminBoundaries(ctx any, filters any) *MockMap_GetAdminBoundaries_Call {
	return &MockMap_GetAdminBoundaries_Call{Call: _e.mock.On("GetAdminBoundaries", ctx, filters)}
}

func (_c *MockMap_GetAdminBoundaries_Call) Run(run func(ctx context.Context, filters models.GetAdminBoundaryFilters)) *MockMap_GetAdminBoundaries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.GetAdminBoundaryFilters
		if args[1] != nil {
			arg1 = args[1].(models.GetAdminBoundaryFilters)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMap_GetAdminBoundaries_Call) Return(adminBoundarys []models.AdminBoundary, err error) *MockMap_GetAdminBoundaries_Call {
	_c.Call.Return(adminBoundarys, err)
	return _c
}

func (_c *MockMap_GetAdminBoundaries_Call) RunAndReturn(run func(ctx context.Context, filters models.GetAdminBoundaryFilters) ([]models.AdminBoundary, error)) *MockMap_GetAdminBoundaries_Call {
	_c.Call.Return(run)
	return _c
}

// GetAdminBoundariesMarksCount provides a mock function for the type MockMap
func (_mock *MockMap) GetAdminBoundariesMarksCount(ctx context.Context, filters models.GetAdminBoundaryMarksCountFilters) ([]models.AdminBoundaryMarksCount, error) {
	ret := _mock.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for GetAdminBoundariesMarksCount")
	}

	var r0 []models.AdminBoundaryMarksCount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetAdminBoundaryMarksCountFilters) ([]models.AdminBoundaryMarksCount, error)); ok {
		return returnFunc(ctx, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetAdminBoundaryMarksCountFilters) []models.AdminBoundaryMarksCount); ok {
		r0 = returnFunc(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.AdminBoundaryMarksCount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.GetAdminBoundaryMarksCountFilters) error); ok {
		r1 = returnFunc(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMap_GetAdminBoundariesMarksCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAdminBoundariesMarksCount'
type MockMap_GetAdminBoundariesMarksCount_Call struct {
	*mock.Call
}

// GetAdminBoundariesMarksCount is a helper method to define mock.On call
//   - ctx context.Context
//   - filters models.GetAdminBoundaryMarksCountFilters
func (_e *MockMap_Expecter) GetAdminBoundariesMarksCount(ctx any, filters any) *MockMap_GetAdminBoundariesMarksCount_Call {
	return &MockMap_GetAdminBoundariesMarksCount_Call{Call: _e.mock.On("GetAdminBoundariesMarksCount", ctx, filters)}
}

func (_c *MockMap_GetAdminBoundariesMarksCount_Call) Run(run func(ctx context.Context, filters models.GetAdminBoundaryMarksCountFilters)) *MockMap_GetAdminBoundariesMarksCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.GetAdminBoundaryMarksCountFilters
		if args[1] != nil {
			arg1 = args[1].(models.GetAdminBoundaryMarksCountFilters)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMap_GetAdminBoundariesMarksCount_Call) Return(adminBoundaryMarksCounts []models.AdminBoundaryMarksCount, err error) *MockMap_GetAdminBoundariesMarksCount_Call {
	_c.Call.Return(adminBoundaryMarksCounts, err)
	return _c
}

func (_c *MockMap_GetAdminBoundariesMarksCount_Call) RunAndReturn(run func(ctx context.Context, filters models.GetAdminBoundaryMarksCountFilters) ([]models.AdminBoundaryMarksCount, error)) *MockMap_GetAdminBoundariesMarksCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetAdminBoundaryById provides a mock function for the type MockMap
func (_mock *MockMap) GetAdminBoundaryById(ctx context.Context, id int) (models.AdminBoundary, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAdminBoundaryById")
	}

	var r0 models.AdminBoundary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (models.AdminBoundary, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) models.AdminBoundary); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(models.AdminBoundary)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMap_GetAdminBoundaryById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAdminBoundaryById'
type MockMap_GetAdminBoundaryById_Call struct {
	*mock.Call
}

// GetAdminBoundaryById is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockMap_Expecter) GetAdminBoundaryById(ctx any, id any) *MockMap_GetAdminBoundaryById_Call {
	return &MockMap_GetAdminBoundaryById_Call{Call: _e.mock.On("GetAdminBoundaryById", ctx, id)}
}

func (_c *MockMap_GetAdminBoundaryById_Call) Run(run func(ctx context.Context, id int)) *MockMap_GetAdminBoundaryById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMap_GetAdminBoundaryById_Call) Return(adminBoundary models.AdminBoundary, err error) *MockMap_GetAdminBoundaryById_Call {
	_c.Call.Return(adminBoundary, err)
	return _c
}

func (_c *MockMap_GetAdminBoundaryById_Call) RunAndReturn(run func(ctx context.Context, id int) (models.AdminBoundary, error)) *MockMap_GetAdminBoundaryById_Call {
	_c.Call.Return(run)
	return _c
}

// GetCities provides a mock function for the type MockMap
func (_mock *MockMap) GetCities(ctx context.Context) ([]models.City, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetCities")
	}

	var r0 []models.City
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.City, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.City); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.City)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMap_GetCities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCities'
type MockMap_GetCities_Call struct {
	*mock.Call
}

// GetCities is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMap_Expecter) GetCities(ctx any) *MockMap_GetCities_Call {
	return &MockMap_GetCities_Call{Call: _e.mock.On("GetCities", ctx)}
}

func (_c *MockMap_GetCities_Call) Run(run func(ctx context.Context)) *MockMap_GetCities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMap_GetCities_Call) Return(citys []models.City, err error) *MockMap_GetCities_Call {
	_c.Call.Return(citys, err)
	return _c
}

func (_c *MockMap_GetCities_Call) RunAndReturn(run func(ctx context.Context) ([]models.City, error)) *MockMap_GetCities_Call {
	_c.Call.Return(run)
	return _c
}

// GetDistricts provides a mock function for the type MockMap
func (_mock *MockMap) GetDistricts(ctx context.Context) ([]models.District, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDistricts")
	}

	var r0 []models.District
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.District, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.District); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.District)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMap_GetDistricts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDistricts'
type MockMap_GetDistricts_Call struct {
	*mock.Call
}

// GetDistricts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMap_Expecter) GetDistricts(ctx any) *MockMap_GetDistricts_Call {
	return &MockMap_GetDistricts_Call{Call: _e.mock.On("GetDistricts", ctx)}
}

func (_c *MockMap_GetDistricts_Call) Run(run func(ctx context.Context)) *MockMap_GetDistricts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMap_GetDistricts_Call) Return(districts []models.District, err error) *MockMap_GetDistricts_Call {
	_c.Call.Return(districts, err)
	return _c
}

func (_c *MockMap_GetDistricts_Call) RunAndReturn(run func(ctx context.Context) ([]models.District, error)) *MockMap_GetDistricts_Call {
	_c.Call.Return(run)
	return _c
}

// GetHeatmap provides a mock function for the type MockMap
func (_mock *MockMap) GetHeatmap(ctx context.Context, filters models.HeatmapFilters) ([]models.HeatmapCell, error) {
	ret := _mock.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for GetHeatmap")
	}

	var r0 []models.HeatmapCell
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.HeatmapFilters) ([]models.HeatmapCell, error)); ok {
		return returnFunc(ctx, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.HeatmapFilters) []models.HeatmapCell); ok {
		r0 = returnFunc(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.HeatmapCell)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.HeatmapFilters) error); ok {
		r1 = returnFunc(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMap_GetHeatmap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHeatmap'
type MockMap_GetHeatmap_Call struct {
	*mock.Call
}

// GetHeatmap is a helper method to define mock.On call
//   - ctx context.Context
//   - filters models.HeatmapFilters
func (_e *MockMap_Expecter) GetHeatmap(ctx any, filters any) *MockMap_GetHeatmap_Call {
	return &MockMap_GetHeatmap_Call{Call: _e.mock.On("GetHeatmap", ctx, filters)}
}

func (_c *MockMap_GetHeatmap_Call) Run(run func(ctx context.Context, filters models.HeatmapFilters)) *MockMap_GetHeatmap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.HeatmapFilters
		if args[1] != nil {
			arg1 = args[1].(models.HeatmapFilters)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMap_GetHeatmap_Call) Return(heatmapCells []models.HeatmapCell, err error) *MockMap_GetHeatmap_Call {
	_c.Call.Return(heatmapCells, err)
	return _c
}

func (_c *MockMap_GetHeatmap_Call) RunAndReturn(run func(ctx context.Context, filters models.HeatmapFilters) ([]models.HeatmapCell, error)) *MockMap_GetHeatmap_Call {
	_c.Call.Return(run)
	return _c
}

// GetRegions provides a mock function for the type MockMap
func (_mock *MockMap) GetRegions(ctx context.Context) ([]models.Region, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRegions")
	}

	var r0 []models.Region
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.Region, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.Region); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Region)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMap_GetRegions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRegions'
type MockMap_GetRegions_Call struct {
	*mock.Call
}

// GetRegions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMap_Expecter) GetRegions(ctx any) *MockMap_GetRegions_Call {
	return &MockMap_GetRegions_Call{Call: _e.mock.On("GetRegions", ctx)}
}

func (_c *MockMap_GetRegions_Call) Run(run func(ctx context.Context)) *MockMap_GetRegions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMap_GetRegions_Call) Return(regions []models.Region, err error) *MockMap_GetRegions_Call {
	_c.Call.Return(regions, err)
	return _c
}

func (_c *MockMap_GetRegions_Call) RunAndReturn(run func(ctx context.Context) ([]models.Region, error)) *MockMap_GetRegions_Call {
	_c.Call.Return(run)
	return _c
}
