DROP TABLE IF EXISTS tasks;

DROP TABLE IF EXISTS marks;

DROP TABLE IF EXISTS districts;

DROP TABLE IF EXISTS cities;

DROP TABLE IF EXISTS regions;

DROP TABLE IF EXISTS types_marks;

DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS task_statuses;