// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package apikey

import (
	"context"

	"github.com/PritOriginal/problem-map-server/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthenticator creates a new instance of MockAuthenticator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthenticator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthenticator {
	mock := &MockAuthenticator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthenticator is an autogenerated mock type for the Authenticator type
type MockAuthenticator struct {
	mock.Mock
}

type MockAuthenticator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthenticator) EXPECT() *MockAuthenticator_Expecter {
	return &MockAuthenticator_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type MockAuthenticator
func (_mock *MockAuthenticator) Authenticate(ctx context.Context, raw string) (models.APIKey, error) {
	ret := _mock.Called(ctx, raw)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 models.APIKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (models.APIKey, error)); ok {
		return returnFunc(ctx, raw)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) models.APIKey); ok {
		r0 = returnFunc(ctx, raw)
	} else {
		r0 = ret.Get(0).(models.APIKey)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, raw)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthenticator_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockAuthenticator_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - raw string
func (_e *MockAuthenticator_Expecter) Authenticate(ctx any, raw any) *MockAuthenticator_Authenticate_Call {
	return &MockAuthenticator_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, raw)}
}

func (_c *MockAuthenticator_Authenticate_Call) Run(run func(ctx context.Context, raw string)) *MockAuthenticator_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthenticator_Authenticate_Call) Return(aPIKey models.APIKey, err error) *MockAuthenticator_Authenticate_Call {
	_c.Call.Return(aPIKey, err)
	return _c
}

func (_c *MockAuthenticator_Authenticate_Call) RunAndReturn(run func(ctx context.Context, raw string) (models.APIKey, error)) *MockAuthenticator_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRecorder creates a new instance of MockRecorder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRecorder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRecorder {
	mock := &MockRecorder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRecorder is an autogenerated mock type for the Recorder type
type MockRecorder struct {
	mock.Mock
}

type MockRecorder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRecorder) EXPECT() *MockRecorder_Expecter {
	return &MockRecorder_Expecter{mock: &_m.Mock}
}

// APIKeyRequest provides a mock function for the type MockRecorder
func (_mock *MockRecorder) APIKeyRequest(keyPrefix string, status int) {
	_mock.Called(keyPrefix, status)
	return
}

// MockRecorder_APIKeyRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'APIKeyRequest'
type MockRecorder_APIKeyRequest_Call struct {
	*mock.Call
}

// APIKeyRequest is a helper method to define mock.On call
//   - keyPrefix string
//   - status int
func (_e *MockRecorder_Expecter) APIKeyRequest(keyPrefix any, status any) *MockRecorder_APIKeyRequest_Call {
	return &MockRecorder_APIKeyRequest_Call{Call: _e.mock.On("APIKeyRequest", keyPrefix, status)}
}

func (_c *MockRecorder_APIKeyRequest_Call) Run(run func(keyPrefix string, status int)) *MockRecorder_APIKeyRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRecorder_APIKeyRequest_Call) Return() *MockRecorder_APIKeyRequest_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRecorder_APIKeyRequest_Call) RunAndReturn(run func(keyPrefix string, status int)) *MockRecorder_APIKeyRequest_Call {
	_c.Run(run)
	return _c
}
