// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package notificationsrest

import (
	"context"

	"github.com/PritOriginal/problem-map-server/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockNotifications creates a new instance of MockNotifications. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotifications(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotifications {
	mock := &MockNotifications{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotifications is an autogenerated mock type for the Notifications type
type MockNotifications struct {
	mock.Mock
}

type MockNotifications_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotifications) EXPECT() *MockNotifications_Expecter {
	return &MockNotifications_Expecter{mock: &_m.Mock}
}

// DeleteDevice provides a mock function for the type MockNotifications
func (_mock *MockNotifications) DeleteDevice(ctx context.Context, userId int, token string) error {
	ret := _mock.Called(ctx, userId, token)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDevice")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = returnFunc(ctx, userId, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotifications_DeleteDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDevice'
type MockNotifications_DeleteDevice_Call struct {
	*mock.Call
}

// DeleteDevice is a helper method to define mock.On call
//   - ctx context.Context
//   - userId int
//   - token string
func (_e *MockNotifications_Expecter) DeleteDevice(ctx any, userId any, token any) *MockNotifications_DeleteDevice_Call {
	return &MockNotifications_DeleteDevice_Call{Call: _e.mock.On("DeleteDevice", ctx, userId, token)}
}

func (_c *MockNotifications_DeleteDevice_Call) Run(run func(ctx context.Context, userId int, token string)) *MockNotifications_DeleteDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNotifications_DeleteDevice_Call) Return(err error) *MockNotifications_DeleteDevice_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotifications_DeleteDevice_Call) RunAndReturn(run func(ctx context.Context, userId int, token string) error) *MockNotifications_DeleteDevice_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockNotifications
func (_mock *MockNotifications) List(ctx context.Context, userId int, filters models.GetNotificationsFilters) (models.Page[models.Notification], error) {
	ret := _mock.Called(ctx, userId, filters)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 models.Page[models.Notification]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.GetNotificationsFilters) (models.Page[models.Notification], error)); ok {
		return returnFunc(ctx, userId, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.GetNotificationsFilters) models.Page[models.Notification]); ok {
		r0 = returnFunc(ctx, userId, filters)
	} else {
		r0 = ret.Get(0).(models.Page[models.Notification])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, models.GetNotificationsFilters) error); ok {
		r1 = returnFunc(ctx, userId, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotifications_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockNotifications_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userId int
//   - filters models.GetNotificationsFilters
func (_e *MockNotifications_Expecter) List(ctx any, userId any, filters any) *MockNotifications_List_Call {
	return &MockNotifications_List_Call{Call: _e.mock.On("List", ctx, userId, filters)}
}

func (_c *MockNotifications_List_Call) Run(run func(ctx context.Context, userId int, filters models.GetNotificationsFilters)) *MockNotifications_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 models.GetNotificationsFilters
		if args[2] != nil {
			arg2 = args[2].(models.GetNotificationsFilters)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNotifications_List_Call) Return(page models.Page[models.Notification], err error) *MockNotifications_List_Call {
	_c.Call.Return(page, err)
	return _c
}

func (_c *MockNotifications_List_Call) RunAndReturn(run func(ctx context.Context, userId int, filters models.GetNotificationsFilters) (models.Page[models.Notification], error)) *MockNotifications_List_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAllRead provides a mock function for the type MockNotifications
func (_mock *MockNotifications) MarkAllRead(ctx context.Context, userId int) (int64, error) {
	ret := _mock.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for MarkAllRead")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (int64, error)); ok {
		return returnFunc(ctx, userId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) int64); ok {
		r0 = returnFunc(ctx, userId)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotifications_MarkAllRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAllRead'
type MockNotifications_MarkAllRead_Call struct {
	*mock.Call
}

// MarkAllRead is a helper method to define mock.On call
//   - ctx context.Context
//   - userId int
func (_e *MockNotifications_Expecter) MarkAllRead(ctx any, userId any) *MockNotifications_MarkAllRead_Call {
	return &MockNotifications_MarkAllRead_Call{Call: _e.mock.On("MarkAllRead", ctx, userId)}
}

func (_c *MockNotifications_MarkAllRead_Call) Run(run func(ctx context.Context, userId int)) *MockNotifications_MarkAllRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotifications_MarkAllRead_Call) Return(n int64, err error) *MockNotifications_MarkAllRead_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockNotifications_MarkAllRead_Call) RunAndReturn(run func(ctx context.Context, userId int) (int64, error)) *MockNotifications_MarkAllRead_Call {
	_c.Call.Return(run)
	return _c
}

// MarkRead provides a mock function for the type MockNotifications
func (_mock *MockNotifications) MarkRead(ctx context.Context, userId int, id int) error {
	ret := _mock.Called(ctx, userId, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkRead")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = returnFunc(ctx, userId, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotifications_MarkRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkRead'
type MockNotifications_MarkRead_Call struct {
	*mock.Call
}

// MarkRead is a helper method to define mock.On call
//   - ctx context.Context
//   - userId int
//   - id int
func (_e *MockNotifications_Expecter) MarkRead(ctx any, userId any, id any) *MockNotifications_MarkRead_Call {
	return &MockNotifications_MarkRead_Call{Call: _e.mock.On("MarkRead", ctx, userId, id)}
}

func (_c *MockNotifications_MarkRead_Call) Run(run func(ctx context.Context, userId int, id int)) *MockNotifications_MarkRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNotifications_MarkRead_Call) Return(err error) *MockNotifications_MarkRead_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotifications_MarkRead_Call) RunAndReturn(run func(ctx context.Context, userId int, id int) error) *MockNotifications_MarkRead_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterDevice provides a mock function for the type MockNotifications
func (_mock *MockNotifications) RegisterDevice(ctx context.Context, device models.UserDevice) (models.UserDevice, error) {
	ret := _mock.Called(ctx, device)

	if len(ret) == 0 {
		panic("no return value specified for RegisterDevice")
	}

	var r0 models.UserDevice
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.UserDevice) (models.UserDevice, error)); ok {
		return returnFunc(ctx, device)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.UserDevice) models.UserDevice); ok {
		r0 = returnFunc(ctx, device)
	} else {
		r0 = ret.Get(0).(models.UserDevice)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.UserDevice) error); ok {
		r1 = returnFunc(ctx, device)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotifications_RegisterDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterDevice'
type MockNotifications_RegisterDevice_Call struct {
	*mock.Call
}

// RegisterDevice is a helper method to define mock.On call
//   - ctx context.Context
//   - device models.UserDevice
func (_e *MockNotifications_Expecter) RegisterDevice(ctx any, device any) *MockNotifications_RegisterDevice_Call {
	return &MockNotifications_RegisterDevice_Call{Call: _e.mock.On("RegisterDevice", ctx, device)}
}

func (_c *MockNotifications_RegisterDevice_Call) Run(run func(ctx context.Context, device models.UserDevice)) *MockNotifications_RegisterDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.UserDevice
		if args[1] != nil {
			arg1 = args[1].(models.UserDevice)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotifications_RegisterDevice_Call) Return(userDevice models.UserDevice, err error) *MockNotifications_RegisterDevice_Call {
	_c.Call.Return(userDevice, err)
	return _c
}

func (_c *MockNotifications_RegisterDevice_Call) RunAndReturn(run func(ctx context.Context, device models.UserDevice) (models.UserDevice, error)) *MockNotifications_RegisterDevice_Call {
	_c.Call.Return(run)
	return _c
}

// UnreadCount provides a mock function for the type MockNotifications
func (_mock *MockNotifications) UnreadCount(ctx context.Context, userId int) (int, error) {
	ret := _mock.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for UnreadCount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (int, error)); ok {
		return returnFunc(ctx, userId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = returnFunc(ctx, userId)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotifications_UnreadCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnreadCount'
type MockNotifications_UnreadCount_Call struct {
	*mock.Call
}

// UnreadCount is a helper method to define mock.On call
//   - ctx context.Context
//   - userId int
func (_e *MockNotifications_Expecter) UnreadCount(ctx any, userId any) *MockNotifications_UnreadCount_Call {
	return &MockNotifications_UnreadCount_Call{Call: _e.mock.On("UnreadCount", ctx, userId)}
}

func (_c *MockNotifications_UnreadCount_Call) Run(run func(ctx context.Context, userId int)) *MockNotifications_UnreadCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotifications_UnreadCount_Call) Return(n int, err error) *MockNotifications_UnreadCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockNotifications_UnreadCount_Call) RunAndReturn(run func(ctx context.Context, userId int) (int, error)) *MockNotifications_UnreadCount_Call {
	_c.Call.Return(run)
	return _c
}
