// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package reportsrest

import (
	"context"

	"github.com/PritOriginal/problem-map-server/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockReports creates a new instance of MockReports. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReports(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReports {
	mock := &MockReports{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReports is an autogenerated mock type for the Reports type
type MockReports struct {
	mock.Mock
}

type MockReports_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReports) EXPECT() *MockReports_Expecter {
	return &MockReports_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockReports
func (_mock *MockReports) Create(ctx context.Context, report models.Report) (models.Report, error) {
	ret := _mock.Called(ctx, report)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.Report
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Report) (models.Report, error)); ok {
		return returnFunc(ctx, report)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Report) models.Report); ok {
		r0 = returnFunc(ctx, report)
	} else {
		r0 = ret.Get(0).(models.Report)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Report) error); ok {
		r1 = returnFunc(ctx, report)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReports_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockReports_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - report models.Report
func (_e *MockReports_Expecter) Create(ctx any, report any) *MockReports_Create_Call {
	return &MockReports_Create_Call{Call: _e.mock.On("Create", ctx, report)}
}

func (_c *MockReports_Create_Call) Run(run func(ctx context.Context, report models.Report)) *MockReports_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Report
		if args[1] != nil {
			arg1 = args[1].(models.Report)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReports_Create_Call) Return(report1 models.Report, err error) *MockReports_Create_Call {
	_c.Call.Return(report1, err)
	return _c
}

func (_c *MockReports_Create_Call) RunAndReturn(run func(ctx context.Context, report models.Report) (models.Report, error)) *MockReports_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ListMine provides a mock function for the type MockReports
func (_mock *MockReports) ListMine(ctx context.Context, reporterId int, p models.Pagination) (models.Page[models.Report], error) {
	ret := _mock.Called(ctx, reporterId, p)

	if len(ret) == 0 {
		panic("no return value specified for ListMine")
	}

	var r0 models.Page[models.Report]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.Pagination) (models.Page[models.Report], error)); ok {
		return returnFunc(ctx, reporterId, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.Pagination) models.Page[models.Report]); ok {
		r0 = returnFunc(ctx, reporterId, p)
	} else {
		r0 = ret.Get(0).(models.Page[models.Report])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, models.Pagination) error); ok {
		r1 = returnFunc(ctx, reporterId, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReports_ListMine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMine'
type MockReports_ListMine_Call struct {
	*mock.Call
}

// ListMine is a helper method to define mock.On call
//   - ctx context.Context
//   - reporterId int
//   - p models.Pagination
func (_e *MockReports_Expecter) ListMine(ctx any, reporterId any, p any) *MockReports_ListMine_Call {
	return &MockReports_ListMine_Call{Call: _e.mock.On("ListMine", ctx, reporterId, p)}
}

func (_c *MockReports_ListMine_Call) Run(run func(ctx context.Context, reporterId int, p models.Pagination)) *MockReports_ListMine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 models.Pagination
		if args[2] != nil {
			arg2 = args[2].(models.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReports_ListMine_Call) Return(page models.Page[models.Report], err error) *MockReports_ListMine_Call {
	_c.Call.Return(page, err)
	return _c
}

func (_c *MockReports_ListMine_Call) RunAndReturn(run func(ctx context.Context, reporterId int, p models.Pagination) (models.Page[models.Report], error)) *MockReports_ListMine_Call {
	_c.Call.Return(run)
	return _c
}

// ListQueue provides a mock function for the type MockReports
func (_mock *MockReports) ListQueue(ctx context.Context, filters models.GetReportsFilters) (models.Page[models.ReportWithTarget], error) {
	ret := _mock.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for ListQueue")
	}

	var r0 models.Page[models.ReportWithTarget]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetReportsFilters) (models.Page[models.ReportWithTarget], error)); ok {
		return returnFunc(ctx, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.GetReportsFilters) models.Page[models.ReportWithTarget]); ok {
		r0 = returnFunc(ctx, filters)
	} else {
		r0 = ret.Get(0).(models.Page[models.ReportWithTarget])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.GetReportsFilters) error); ok {
		r1 = returnFunc(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReports_ListQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListQueue'
type MockReports_ListQueue_Call struct {
	*mock.Call
}

// ListQueue is a helper method to define mock.On call
//   - ctx context.Context
//   - filters models.GetReportsFilters
func (_e *MockReports_Expecter) ListQueue(ctx any, filters any) *MockReports_ListQueue_Call {
	return &MockReports_ListQueue_Call{Call: _e.mock.On("ListQueue", ctx, filters)}
}

func (_c *MockReports_ListQueue_Call) Run(run func(ctx context.Context, filters models.GetReportsFilters)) *MockReports_ListQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.GetReportsFilters
		if args[1] != nil {
			arg1 = args[1].(models.GetReportsFilters)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReports_ListQueue_Call) Return(page models.Page[models.ReportWithTarget], err error) *MockReports_ListQueue_Call {
	_c.Call.Return(page, err)
	return _c
}

func (_c *MockReports_ListQueue_Call) RunAndReturn(run func(ctx context.Context, filters models.GetReportsFilters) (models.Page[models.ReportWithTarget], error)) *MockReports_ListQueue_Call {
	_c.Call.Return(run)
	return _c
}

// Resolve provides a mock function for the type MockReports
func (_mock *MockReports) Resolve(ctx context.Context, actor models.Actor, id int, status models.ReportStatus) (models.Report, error) {
	ret := _mock.Called(ctx, actor, id, status)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 models.Report
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Actor, int, models.ReportStatus) (models.Report, error)); ok {
		return returnFunc(ctx, actor, id, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Actor, int, models.ReportStatus) models.Report); ok {
		r0 = returnFunc(ctx, actor, id, status)
	} else {
		r0 = ret.Get(0).(models.Report)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Actor, int, models.ReportStatus) error); ok {
		r1 = returnFunc(ctx, actor, id, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReports_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockReports_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - ctx context.Context
//   - actor models.Actor
//   - id int
//   - status models.ReportStatus
func (_e *MockReports_Expecter) Resolve(ctx any, actor any, id any, status any) *MockReports_Resolve_Call {
	return &MockReports_Resolve_Call{Call: _e.mock.On("Resolve", ctx, actor, id, status)}
}

func (_c *MockReports_Resolve_Call) Run(run func(ctx context.Context, actor models.Actor, id int, status models.ReportStatus)) *MockReports_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Actor
		if args[1] != nil {
			arg1 = args[1].(models.Actor)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 models.ReportStatus
		if args[3] != nil {
			arg3 = args[3].(models.ReportStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockReports_Resolve_Call) Return(report models.Report, err error) *MockReports_Resolve_Call {
	_c.Call.Return(report, err)
	return _c
}

func (_c *MockReports_Resolve_Call) RunAndReturn(run func(ctx context.Context, actor models.Actor, id int, status models.ReportStatus) (models.Report, error)) *MockReports_Resolve_Call {
	_c.Call.Return(run)
	return _c
}
