// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package analyticsrest

import (
	"context"

	"github.com/PritOriginal/problem-map-server/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAnalytics creates a new instance of MockAnalytics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAnalytics(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAnalytics {
	mock := &MockAnalytics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAnalytics is an autogenerated mock type for the Analytics type
type MockAnalytics struct {
	mock.Mock
}

type MockAnalytics_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAnalytics) EXPECT() *MockAnalytics_Expecter {
	return &MockAnalytics_Expecter{mock: &_m.Mock}
}

// GetKPI provides a mock function for the type MockAnalytics
func (_mock *MockAnalytics) GetKPI(ctx context.Context, filters models.AnalyticsFilters) (models.KPI, error) {
	ret := _mock.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for GetKPI")
	}

	var r0 models.KPI
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.AnalyticsFilters) (models.KPI, error)); ok {
		return returnFunc(ctx, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.AnalyticsFilters) models.KPI); ok {
		r0 = returnFunc(ctx, filters)
	} else {
		r0 = ret.Get(0).(models.KPI)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.AnalyticsFilters) error); ok {
		r1 = returnFunc(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalytics_GetKPI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKPI'
type MockAnalytics_GetKPI_Call struct {
	*mock.Call
}

// GetKPI is a helper method to define mock.On call
//   - ctx context.Context
//   - filters models.AnalyticsFilters
func (_e *MockAnalytics_Expecter) GetKPI(ctx any, filters any) *MockAnalytics_GetKPI_Call {
	return &MockAnalytics_GetKPI_Call{Call: _e.mock.On("GetKPI", ctx, filters)}
}

func (_c *MockAnalytics_GetKPI_Call) Run(run func(ctx context.Context, filters models.AnalyticsFilters)) *MockAnalytics_GetKPI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.AnalyticsFilters
		if args[1] != nil {
			arg1 = args[1].(models.AnalyticsFilters)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAnalytics_GetKPI_Call) Return(kPI models.KPI, err error) *MockAnalytics_GetKPI_Call {
	_c.Call.Return(kPI, err)
	return _c
}

func (_c *MockAnalytics_GetKPI_Call) RunAndReturn(run func(ctx context.Context, filters models.AnalyticsFilters) (models.KPI, error)) *MockAnalytics_GetKPI_Call {
	_c.Call.Return(run)
	return _c
}

// GetTimeseries provides a mock function for the type MockAnalytics
func (_mock *MockAnalytics) GetTimeseries(ctx context.Context, filters models.TimeseriesFilters) ([]models.TimeseriesPoint, error) {
	ret := _mock.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for GetTimeseries")
	}

	var r0 []models.TimeseriesPoint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.TimeseriesFilters) ([]models.TimeseriesPoint, error)); ok {
		return returnFunc(ctx, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.TimeseriesFilters) []models.TimeseriesPoint); ok {
		r0 = returnFunc(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.TimeseriesPoint)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.TimeseriesFilters) error); ok {
		r1 = returnFunc(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalytics_GetTimeseries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTimeseries'
type MockAnalytics_GetTimeseries_Call struct {
	*mock.Call
}

// GetTimeseries is a helper method to define mock.On call
//   - ctx context.Context
//   - filters models.TimeseriesFilters
func (_e *MockAnalytics_Expecter) GetTimeseries(ctx any, filters any) *MockAnalytics_GetTimeseries_Call {
	return &MockAnalytics_GetTimeseries_Call{Call: _e.mock.On("GetTimeseries", ctx, filters)}
}

func (_c *MockAnalytics_GetTimeseries_Call) Run(run func(ctx context.Context, filters models.TimeseriesFilters)) *MockAnalytics_GetTimeseries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.TimeseriesFilters
		if args[1] != nil {
			arg1 = args[1].(models.TimeseriesFilters)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAnalytics_GetTimeseries_Call) Return(timeseriesPoints []models.TimeseriesPoint, err error) *MockAnalytics_GetTimeseries_Call {
	_c.Call.Return(timeseriesPoints, err)
	return _c
}

func (_c *MockAnalytics_GetTimeseries_Call) RunAndReturn(run func(ctx context.Context, filters models.TimeseriesFilters) ([]models.TimeseriesPoint, error)) *MockAnalytics_GetTimeseries_Call {
	_c.Call.Return(run)
	return _c
}

// GetTopTypes provides a mock function for the type MockAnalytics
func (_mock *MockAnalytics) GetTopTypes(ctx context.Context, filters models.TopTypesFilters) ([]models.TopType, error) {
	ret := _mock.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for GetTopTypes")
	}

	var r0 []models.TopType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.TopTypesFilters) ([]models.TopType, error)); ok {
		return returnFunc(ctx, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.TopTypesFilters) []models.TopType); ok {
		r0 = returnFunc(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.TopType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.TopTypesFilters) error); ok {
		r1 = returnFunc(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalytics_GetTopTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTopTypes'
type MockAnalytics_GetTopTypes_Call struct {
	*mock.Call
}

// GetTopTypes is a helper method to define mock.On call
//   - ctx context.Context
//   - filters models.TopTypesFilters
func (_e *MockAnalytics_Expecter) GetTopTypes(ctx any, filters any) *MockAnalytics_GetTopTypes_Call {
	return &MockAnalytics_GetTopTypes_Call{Call: _e.mock.On("GetTopTypes", ctx, filters)}
}

func (_c *MockAnalytics_GetTopTypes_Call) Run(run func(ctx context.Context, filters models.TopTypesFilters)) *MockAnalytics_GetTopTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.TopTypesFilters
		if args[1] != nil {
			arg1 = args[1].(models.TopTypesFilters)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAnalytics_GetTopTypes_Call) Return(topTypes []models.TopType, err error) *MockAnalytics_GetTopTypes_Call {
	_c.Call.Return(topTypes, err)
	return _c
}

func (_c *MockAnalytics_GetTopTypes_Call) RunAndReturn(run func(ctx context.Context, filters models.TopTypesFilters) ([]models.TopType, error)) *MockAnalytics_GetTopTypes_Call {
	_c.Call.Return(run)
	return _c
}
