// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package syncrest

import (
	"context"

	"github.com/PritOriginal/problem-map-server/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSync creates a new instance of MockSync. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSync(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSync {
	mock := &MockSync{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSync is an autogenerated mock type for the Sync type
type MockSync struct {
	mock.Mock
}

type MockSync_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSync) EXPECT() *MockSync_Expecter {
	return &MockSync_Expecter{mock: &_m.Mock}
}

// GetUserSync provides a mock function for the type MockSync
func (_mock *MockSync) GetUserSync(ctx context.Context, userId int, filters models.UserSyncFilters) (models.UserSync, error) {
	ret := _mock.Called(ctx, userId, filters)

	if len(ret) == 0 {
		panic("no return value specified for GetUserSync")
	}

	var r0 models.UserSync
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.UserSyncFilters) (models.UserSync, error)); ok {
		return returnFunc(ctx, userId, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.UserSyncFilters) models.UserSync); ok {
		r0 = returnFunc(ctx, userId, filters)
	} else {
		r0 = ret.Get(0).(models.UserSync)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, models.UserSyncFilters) error); ok {
		r1 = returnFunc(ctx, userId, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSync_GetUserSync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserSync'
type MockSync_GetUserSync_Call struct {
	*mock.Call
}

// GetUserSync is a helper method to define mock.On call
//   - ctx context.Context
//   - userId int
//   - filters models.UserSyncFilters
func (_e *MockSync_Expecter) GetUserSync(ctx any, userId any, filters any) *MockSync_GetUserSync_Call {
	return &MockSync_GetUserSync_Call{Call: _e.mock.On("GetUserSync", ctx, userId, filters)}
}

func (_c *MockSync_GetUserSync_Call) Run(run func(ctx context.Context, userId int, filters models.UserSyncFilters)) *MockSync_GetUserSync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 models.UserSyncFilters
		if args[2] != nil {
			arg2 = args[2].(models.UserSyncFilters)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSync_GetUserSync_Call) Return(userSync models.UserSync, err error) *MockSync_GetUserSync_Call {
	_c.Call.Return(userSync, err)
	return _c
}

func (_c *MockSync_GetUserSync_Call) RunAndReturn(run func(ctx context.Context, userId int, filters models.UserSyncFilters) (models.UserSync, error)) *MockSync_GetUserSync_Call {
	_c.Call.Return(run)
	return _c
}
