// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package commentsrest

import (
	"context"

	"github.com/PritOriginal/problem-map-server/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockComments creates a new instance of MockComments. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockComments(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockComments {
	mock := &MockComments{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockComments is an autogenerated mock type for the Comments type
type MockComments struct {
	mock.Mock
}

type MockComments_Expecter struct {
	mock *mock.Mock
}

func (_m *MockComments) EXPECT() *MockComments_Expecter {
	return &MockComments_Expecter{mock: &_m.Mock}
}

// AddComment provides a mock function for the type MockComments
func (_mock *MockComments) AddComment(ctx context.Context, comment models.Comment) (models.Comment, error) {
	ret := _mock.Called(ctx, comment)

	if len(ret) == 0 {
		panic("no return value specified for AddComment")
	}

	var r0 models.Comment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Comment) (models.Comment, error)); ok {
		return returnFunc(ctx, comment)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Comment) models.Comment); ok {
		r0 = returnFunc(ctx, comment)
	} else {
		r0 = ret.Get(0).(models.Comment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Comment) error); ok {
		r1 = returnFunc(ctx, comment)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockComments_AddComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddComment'
type MockComments_AddComment_Call struct {
	*mock.Call
}

// AddComment is a helper method to define mock.On call
//   - ctx context.Context
//   - comment models.Comment
func (_e *MockComments_Expecter) AddComment(ctx any, comment any) *MockComments_AddComment_Call {
	return &MockComments_AddComment_Call{Call: _e.mock.On("AddComment", ctx, comment)}
}

func (_c *MockComments_AddComment_Call) Run(run func(ctx context.Context, comment models.Comment)) *MockComments_AddComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Comment
		if args[1] != nil {
			arg1 = args[1].(models.Comment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockComments_AddComment_Call) Return(comment1 models.Comment, err error) *MockComments_AddComment_Call {
	_c.Call.Return(comment1, err)
	return _c
}

func (_c *MockComments_AddComment_Call) RunAndReturn(run func(ctx context.Context, comment models.Comment) (models.Comment, error)) *MockComments_AddComment_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteComment provides a mock function for the type MockComments
func (_mock *MockComments) DeleteComment(ctx context.Context, actor models.Actor, id int) error {
	ret := _mock.Called(ctx, actor, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Actor, int) error); ok {
		r0 = returnFunc(ctx, actor, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockComments_DeleteComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteComment'
type MockComments_DeleteComment_Call struct {
	*mock.Call
}

// DeleteComment is a helper method to define mock.On call
//   - ctx context.Context
//   - actor models.Actor
//   - id int
func (_e *MockComments_Expecter) DeleteComment(ctx any, actor any, id any) *MockComments_DeleteComment_Call {
	return &MockComments_DeleteComment_Call{Call: _e.mock.On("DeleteComment", ctx, actor, id)}
}

func (_c *MockComments_DeleteComment_Call) Run(run func(ctx context.Context, actor models.Actor, id int)) *MockComments_DeleteComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Actor
		if args[1] != nil {
			arg1 = args[1].(models.Actor)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockComments_DeleteComment_Call) Return(err error) *MockComments_DeleteComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockComments_DeleteComment_Call) RunAndReturn(run func(ctx context.Context, actor models.Actor, id int) error) *MockComments_DeleteComment_Call {
	_c.Call.Return(run)
	return _c
}

// ListComments provides a mock function for the type MockComments
func (_mock *MockComments) ListComments(ctx context.Context, markId int, p models.Pagination) (models.Page[models.Comment], error) {
	ret := _mock.Called(ctx, markId, p)

	if len(ret) == 0 {
		panic("no return value specified for ListComments")
	}

	var r0 models.Page[models.Comment]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.Pagination) (models.Page[models.Comment], error)); ok {
		return returnFunc(ctx, markId, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, models.Pagination) models.Page[models.Comment]); ok {
		r0 = returnFunc(ctx, markId, p)
	} else {
		r0 = ret.Get(0).(models.Page[models.Comment])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, models.Pagination) error); ok {
		r1 = returnFunc(ctx, markId, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockComments_ListComments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListComments'
type MockComments_ListComments_Call struct {
	*mock.Call
}

// ListComments is a helper method to define mock.On call
//   - ctx context.Context
//   - markId int
//   - p models.Pagination
func (_e *MockComments_Expecter) ListComments(ctx any, markId any, p any) *MockComments_ListComments_Call {
	return &MockComments_ListComments_Call{Call: _e.mock.On("ListComments", ctx, markId, p)}
}

func (_c *MockComments_ListComments_Call) Run(run func(ctx context.Context, markId int, p models.Pagination)) *MockComments_ListComments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 models.Pagination
		if args[2] != nil {
			arg2 = args[2].(models.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockComments_ListComments_Call) Return(page models.Page[models.Comment], err error) *MockComments_ListComments_Call {
	_c.Call.Return(page, err)
	return _c
}

func (_c *MockComments_ListComments_Call) RunAndReturn(run func(ctx context.Context, markId int, p models.Pagination) (models.Page[models.Comment], error)) *MockComments_ListComments_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateComment provides a mock function for the type MockComments
func (_mock *MockComments) UpdateComment(ctx context.Context, actor models.Actor, id int, body string) (models.Comment, error) {
	ret := _mock.Called(ctx, actor, id, body)

	if len(ret) == 0 {
		panic("no return value specified for UpdateComment")
	}

	var r0 models.Comment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Actor, int, string) (models.Comment, error)); ok {
		return returnFunc(ctx, actor, id, body)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Actor, int, string) models.Comment); ok {
		r0 = returnFunc(ctx, actor, id, body)
	} else {
		r0 = ret.Get(0).(models.Comment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Actor, int, string) error); ok {
		r1 = returnFunc(ctx, actor, id, body)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockComments_UpdateComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateComment'
type MockComments_UpdateComment_Call struct {
	*mock.Call
}

// UpdateComment is a helper method to define mock.On call
//   - ctx context.Context
//   - actor models.Actor
//   - id int
//   - body string
func (_e *MockComments_Expecter) UpdateComment(ctx any, actor any, id any, body any) *MockComments_UpdateComment_Call {
	return &MockComments_UpdateComment_Call{Call: _e.mock.On("UpdateComment", ctx, actor, id, body)}
}

func (_c *MockComments_UpdateComment_Call) Run(run func(ctx context.Context, actor models.Actor, id int, body string)) *MockComments_UpdateComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Actor
		if args[1] != nil {
			arg1 = args[1].(models.Actor)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockComments_UpdateComment_Call) Return(comment models.Comment, err error) *MockComments_UpdateComment_Call {
	_c.Call.Return(comment, err)
	return _c
}

func (_c *MockComments_UpdateComment_Call) RunAndReturn(run func(ctx context.Context, actor models.Actor, id int, body string) (models.Comment, error)) *MockComments_UpdateComment_Call {
	_c.Call.Return(run)
	return _c
}
