// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package webhooksrest

import (
	"context"

	"github.com/PritOriginal/problem-map-server/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWebhooks creates a new instance of MockWebhooks. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWebhooks(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWebhooks {
	mock := &MockWebhooks{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWebhooks is an autogenerated mock type for the Webhooks type
type MockWebhooks struct {
	mock.Mock
}

type MockWebhooks_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWebhooks) EXPECT() *MockWebhooks_Expecter {
	return &MockWebhooks_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockWebhooks
func (_mock *MockWebhooks) Create(ctx context.Context, actor models.Actor, w models.Webhook) (models.Webhook, error) {
	ret := _mock.Called(ctx, actor, w)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.Webhook
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Actor, models.Webhook) (models.Webhook, error)); ok {
		return returnFunc(ctx, actor, w)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Actor, models.Webhook) models.Webhook); ok {
		r0 = returnFunc(ctx, actor, w)
	} else {
		r0 = ret.Get(0).(models.Webhook)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Actor, models.Webhook) error); ok {
		r1 = returnFunc(ctx, actor, w)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebhooks_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockWebhooks_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - actor models.Actor
//   - w models.Webhook
func (_e *MockWebhooks_Expecter) Create(ctx any, actor any, w any) *MockWebhooks_Create_Call {
	return &MockWebhooks_Create_Call{Call: _e.mock.On("Create", ctx, actor, w)}
}

func (_c *MockWebhooks_Create_Call) Run(run func(ctx context.Context, actor models.Actor, w models.Webhook)) *MockWebhooks_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Actor
		if args[1] != nil {
			arg1 = args[1].(models.Actor)
		}
		var arg2 models.Webhook
		if args[2] != nil {
			arg2 = args[2].(models.Webhook)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWebhooks_Create_Call) Return(webhook models.Webhook, err error) *MockWebhooks_Create_Call {
	_c.Call.Return(webhook, err)
	return _c
}

func (_c *MockWebhooks_Create_Call) RunAndReturn(run func(ctx context.Context, actor models.Actor, w models.Webhook) (models.Webhook, error)) *MockWebhooks_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockWebhooks
func (_mock *MockWebhooks) Delete(ctx context.Context, actor models.Actor, id int) error {
	ret := _mock.Called(ctx, actor, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Actor, int) error); ok {
		r0 = returnFunc(ctx, actor, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWebhooks_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockWebhooks_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - actor models.Actor
//   - id int
func (_e *MockWebhooks_Expecter) Delete(ctx any, actor any, id any) *MockWebhooks_Delete_Call {
	return &MockWebhooks_Delete_Call{Call: _e.mock.On("Delete", ctx, actor, id)}
}

func (_c *MockWebhooks_Delete_Call) Run(run func(ctx context.Context, actor models.Actor, id int)) *MockWebhooks_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Actor
		if args[1] != nil {
			arg1 = args[1].(models.Actor)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWebhooks_Delete_Call) Return(err error) *MockWebhooks_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWebhooks_Delete_Call) RunAndReturn(run func(ctx context.Context, actor models.Actor, id int) error) *MockWebhooks_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockWebhooks
func (_mock *MockWebhooks) List(ctx context.Context, actor models.Actor) ([]models.Webhook, error) {
	ret := _mock.Called(ctx, actor)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Webhook
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Actor) ([]models.Webhook, error)); ok {
		return returnFunc(ctx, actor)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Actor) []models.Webhook); ok {
		r0 = returnFunc(ctx, actor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Webhook)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Actor) error); ok {
		r1 = returnFunc(ctx, actor)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebhooks_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockWebhooks_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - actor models.Actor
func (_e *MockWebhooks_Expecter) List(ctx any, actor any) *MockWebhooks_List_Call {
	return &MockWebhooks_List_Call{Call: _e.mock.On("List", ctx, actor)}
}

func (_c *MockWebhooks_List_Call) Run(run func(ctx context.Context, actor models.Actor)) *MockWebhooks_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Actor
		if args[1] != nil {
			arg1 = args[1].(models.Actor)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWebhooks_List_Call) Return(webhooks []models.Webhook, err error) *MockWebhooks_List_Call {
	_c.Call.Return(webhooks, err)
	return _c
}

func (_c *MockWebhooks_List_Call) RunAndReturn(run func(ctx context.Context, actor models.Actor) ([]models.Webhook, error)) *MockWebhooks_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListDeliveries provides a mock function for the type MockWebhooks
func (_mock *MockWebhooks) ListDeliveries(ctx context.Context, actor models.Actor, id int, p models.Pagination) (models.Page[models.WebhookDelivery], error) {
	ret := _mock.Called(ctx, actor, id, p)

	if len(ret) == 0 {
		panic("no return value specified for ListDeliveries")
	}

	var r0 models.Page[models.WebhookDelivery]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Actor, int, models.Pagination) (models.Page[models.WebhookDelivery], error)); ok {
		return returnFunc(ctx, actor, id, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Actor, int, models.Pagination) models.Page[models.WebhookDelivery]); ok {
		r0 = returnFunc(ctx, actor, id, p)
	} else {
		r0 = ret.Get(0).(models.Page[models.WebhookDelivery])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Actor, int, models.Pagination) error); ok {
		r1 = returnFunc(ctx, actor, id, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebhooks_ListDeliveries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDeliveries'
type MockWebhooks_ListDeliveries_Call struct {
	*mock.Call
}

// ListDeliveries is a helper method to define mock.On call
//   - ctx context.Context
//   - actor models.Actor
//   - id int
//   - p models.Pagination
func (_e *MockWebhooks_Expecter) ListDeliveries(ctx any, actor any, id any, p any) *MockWebhooks_ListDeliveries_Call {
	return &MockWebhooks_ListDeliveries_Call{Call: _e.mock.On("ListDeliveries", ctx, actor, id, p)}
}

func (_c *MockWebhooks_ListDeliveries_Call) Run(run func(ctx context.Context, actor models.Actor, id int, p models.Pagination)) *MockWebhooks_ListDeliveries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Actor
		if args[1] != nil {
			arg1 = args[1].(models.Actor)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 models.Pagination
		if args[3] != nil {
			arg3 = args[3].(models.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockWebhooks_ListDeliveries_Call) Return(page models.Page[models.WebhookDelivery], err error) *MockWebhooks_ListDeliveries_Call {
	_c.Call.Return(page, err)
	return _c
}

func (_c *MockWebhooks_ListDeliveries_Call) RunAndReturn(run func(ctx context.Context, actor models.Actor, id int, p models.Pagination) (models.Page[models.WebhookDelivery], error)) *MockWebhooks_ListDeliveries_Call {
	_c.Call.Return(run)
	return _c
}

// SendTest provides a mock function for the type MockWebhooks
func (_mock *MockWebhooks) SendTest(ctx context.Context, actor models.Actor, id int) (models.WebhookDelivery, error) {
	ret := _mock.Called(ctx, actor, id)

	if len(ret) == 0 {
		panic("no return value specified for SendTest")
	}

	var r0 models.WebhookDelivery
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Actor, int) (models.WebhookDelivery, error)); ok {
		return returnFunc(ctx, actor, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Actor, int) models.WebhookDelivery); ok {
		r0 = returnFunc(ctx, actor, id)
	} else {
		r0 = ret.Get(0).(models.WebhookDelivery)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Actor, int) error); ok {
		r1 = returnFunc(ctx, actor, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebhooks_SendTest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendTest'
type MockWebhooks_SendTest_Call struct {
	*mock.Call
}

// SendTest is a helper method to define mock.On call
//   - ctx context.Context
//   - actor models.Actor
//   - id int
func (_e *MockWebhooks_Expecter) SendTest(ctx any, actor any, id any) *MockWebhooks_SendTest_Call {
	return &MockWebhooks_SendTest_Call{Call: _e.mock.On("SendTest", ctx, actor, id)}
}

func (_c *MockWebhooks_SendTest_Call) Run(run func(ctx context.Context, actor models.Actor, id int)) *MockWebhooks_SendTest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Actor
		if args[1] != nil {
			arg1 = args[1].(models.Actor)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWebhooks_SendTest_Call) Return(webhookDelivery models.WebhookDelivery, err error) *MockWebhooks_SendTest_Call {
	_c.Call.Return(webhookDelivery, err)
	return _c
}

func (_c *MockWebhooks_SendTest_Call) RunAndReturn(run func(ctx context.Context, actor models.Actor, id int) (models.WebhookDelivery, error)) *MockWebhooks_SendTest_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockWebhooks
func (_mock *MockWebhooks) Update(ctx context.Context, actor models.Actor, id int, upd models.WebhookUpdate) (models.Webhook, error) {
	ret := _mock.Called(ctx, actor, id, upd)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 models.Webhook
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Actor, int, models.WebhookUpdate) (models.Webhook, error)); ok {
		return returnFunc(ctx, actor, id, upd)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Actor, int, models.WebhookUpdate) models.Webhook); ok {
		r0 = returnFunc(ctx, actor, id, upd)
	} else {
		r0 = ret.Get(0).(models.Webhook)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Actor, int, models.WebhookUpdate) error); ok {
		r1 = returnFunc(ctx, actor, id, upd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebhooks_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockWebhooks_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - actor models.Actor
//   - id int
//   - upd models.WebhookUpdate
func (_e *MockWebhooks_Expecter) Update(ctx any, actor any, id any, upd any) *MockWebhooks_Update_Call {
	return &MockWebhooks_Update_Call{Call: _e.mock.On("Update", ctx, actor, id, upd)}
}

func (_c *MockWebhooks_Update_Call) Run(run func(ctx context.Context, actor models.Actor, id int, upd models.WebhookUpdate)) *MockWebhooks_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Actor
		if args[1] != nil {
			arg1 = args[1].(models.Actor)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 models.WebhookUpdate
		if args[3] != nil {
			arg3 = args[3].(models.WebhookUpdate)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockWebhooks_Update_Call) Return(webhook models.Webhook, err error) *MockWebhooks_Update_Call {
	_c.Call.Return(webhook, err)
	return _c
}

func (_c *MockWebhooks_Update_Call) RunAndReturn(run func(ctx context.Context, actor models.Actor, id int, upd models.WebhookUpdate) (models.Webhook, error)) *MockWebhooks_Update_Call {
	_c.Call.Return(run)
	return _c
}
