// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package middleware

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockVersionSource creates a new instance of MockVersionSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVersionSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVersionSource {
	mock := &MockVersionSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVersionSource is an autogenerated mock type for the VersionSource type
type MockVersionSource struct {
	mock.Mock
}

type MockVersionSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVersionSource) EXPECT() *MockVersionSource_Expecter {
	return &MockVersionSource_Expecter{mock: &_m.Mock}
}

// AuthVersion provides a mock function for the type MockVersionSource
func (_mock *MockVersionSource) AuthVersion(ctx context.Context, userID int) (int64, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for AuthVersion")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (int64, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) int64); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVersionSource_AuthVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthVersion'
type MockVersionSource_AuthVersion_Call struct {
	*mock.Call
}

// AuthVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockVersionSource_Expecter) AuthVersion(ctx any, userID any) *MockVersionSource_AuthVersion_Call {
	return &MockVersionSource_AuthVersion_Call{Call: _e.mock.On("AuthVersion", ctx, userID)}
}

func (_c *MockVersionSource_AuthVersion_Call) Run(run func(ctx context.Context, userID int)) *MockVersionSource_AuthVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVersionSource_AuthVersion_Call) Return(n int64, err error) *MockVersionSource_AuthVersion_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockVersionSource_AuthVersion_Call) RunAndReturn(run func(ctx context.Context, userID int) (int64, error)) *MockVersionSource_AuthVersion_Call {
	_c.Call.Return(run)
	return _c
}

// IncrAuthVersion provides a mock function for the type MockVersionSource
func (_mock *MockVersionSource) IncrAuthVersion(ctx context.Context, userID int) (int64, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for IncrAuthVersion")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (int64, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) int64); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVersionSource_IncrAuthVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrAuthVersion'
type MockVersionSource_IncrAuthVersion_Call struct {
	*mock.Call
}

// IncrAuthVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockVersionSource_Expecter) IncrAuthVersion(ctx any, userID any) *MockVersionSource_IncrAuthVersion_Call {
	return &MockVersionSource_IncrAuthVersion_Call{Call: _e.mock.On("IncrAuthVersion", ctx, userID)}
}

func (_c *MockVersionSource_IncrAuthVersion_Call) Run(run func(ctx context.Context, userID int)) *MockVersionSource_IncrAuthVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVersionSource_IncrAuthVersion_Call) Return(n int64, err error) *MockVersionSource_IncrAuthVersion_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockVersionSource_IncrAuthVersion_Call) RunAndReturn(run func(ctx context.Context, userID int) (int64, error)) *MockVersionSource_IncrAuthVersion_Call {
	_c.Call.Return(run)
	return _c
}
