// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecase

import (
	"context"

	"github.com/avito-tech/go-transaction-manager/trm/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// Do provides a mock function for the type MockManager
func (_mock *MockManager) Do(context1 context.Context, fn func(ctx context.Context) error) error {
	ret := _mock.Called(context1, fn)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ctx context.Context) error) error); ok {
		r0 = returnFunc(context1, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockManager_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockManager_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - context1 context.Context
//   - fn func(ctx context.Context) error
func (_e *MockManager_Expecter) Do(context1 interface{}, fn interface{}) *MockManager_Do_Call {
	return &MockManager_Do_Call{Call: _e.mock.On("Do", context1, fn)}
}

func (_c *MockManager_Do_Call) Run(run func(context1 context.Context, fn func(ctx context.Context) error)) *MockManager_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ctx context.Context) error
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManager_Do_Call) Return(err error) *MockManager_Do_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockManager_Do_Call) RunAndReturn(run func(context1 context.Context, fn func(ctx context.Context) error) error) *MockManager_Do_Call {
	_c.Call.Return(run)
	return _c
}

// DoWithSettings provides a mock function for the type MockManager
func (_mock *MockManager) DoWithSettings(context1 context.Context, settings trm.Settings, fn func(ctx context.Context) error) error {
	ret := _mock.Called(context1, settings, fn)

	if len(ret) == 0 {
		panic("no return value specified for DoWithSettings")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, trm.Settings, func(ctx context.Context) error) error); ok {
		r0 = returnFunc(context1, settings, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockManager_DoWithSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoWithSettings'
type MockManager_DoWithSettings_Call struct {
	*mock.Call
}

// DoWithSettings is a helper method to define mock.On call
//   - context1 context.Context
//   - settings trm.Settings
//   - fn func(ctx context.Context) error
func (_e *MockManager_Expecter) DoWithSettings(context1 interface{}, settings interface{}, fn interface{}) *MockManager_DoWithSettings_Call {
	return &MockManager_DoWithSettings_Call{Call: _e.mock.On("DoWithSettings", context1, settings, fn)}
}

func (_c *MockManager_DoWithSettings_Call) Run(run func(context1 context.Context, settings trm.Settings, fn func(ctx context.Context) error)) *MockManager_DoWithSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 trm.Settings
		if args[1] != nil {
			arg1 = args[1].(trm.Settings)
		}
		var arg2 func(ctx context.Context) error
		if args[2] != nil {
			arg2 = args[2].(func(ctx context.Context) error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockManager_DoWithSettings_Call) Return(err error) *MockManager_DoWithSettings_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockManager_DoWithSettings_Call) RunAndReturn(run func(context1 context.Context, settings trm.Settings, fn func(ctx context.Context) error) error) *MockManager_DoWithSettings_Call {
	_c.Call.Return(run)
	return _c
}
