// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cache

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCacher creates a new instance of MockCacher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCacher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCacher {
	mock := &MockCacher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCacher is an autogenerated mock type for the Cacher type
type MockCacher struct {
	mock.Mock
}

type MockCacher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCacher) EXPECT() *MockCacher_Expecter {
	return &MockCacher_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockCacher
func (_mock *MockCacher) Get(ctx context.Context, key string, v any) error {
	ret := _mock.Called(ctx, key, v)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) error); ok {
		r0 = returnFunc(ctx, key, v)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCacher_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCacher_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - v any
func (_e *MockCacher_Expecter) Get(ctx interface{}, key interface{}, v interface{}) *MockCacher_Get_Call {
	return &MockCacher_Get_Call{Call: _e.mock.On("Get", ctx, key, v)}
}

func (_c *MockCacher_Get_Call) Run(run func(ctx context.Context, key string, v any)) *MockCacher_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCacher_Get_Call) Return(err error) *MockCacher_Get_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCacher_Get_Call) RunAndReturn(run func(ctx context.Context, key string, v any) error) *MockCacher_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetBytes provides a mock function for the type MockCacher
func (_mock *MockCacher) GetBytes(ctx context.Context, key string) ([]byte, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetBytes")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCacher_GetBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBytes'
type MockCacher_GetBytes_Call struct {
	*mock.Call
}

// GetBytes is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockCacher_Expecter) GetBytes(ctx interface{}, key interface{}) *MockCacher_GetBytes_Call {
	return &MockCacher_GetBytes_Call{Call: _e.mock.On("GetBytes", ctx, key)}
}

func (_c *MockCacher_GetBytes_Call) Run(run func(ctx context.Context, key string)) *MockCacher_GetBytes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCacher_GetBytes_Call) Return(bytes []byte, err error) *MockCacher_GetBytes_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockCacher_GetBytes_Call) RunAndReturn(run func(ctx context.Context, key string) ([]byte, error)) *MockCacher_GetBytes_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockCacher
func (_mock *MockCacher) Set(ctx context.Context, key string, value any, expiration time.Duration) error {
	ret := _mock.Called(ctx, key, value, expiration)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, time.Duration) error); ok {
		r0 = returnFunc(ctx, key, value, expiration)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCacher_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockCacher_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value any
//   - expiration time.Duration
func (_e *MockCacher_Expecter) Set(ctx interface{}, key interface{}, value interface{}, expiration interface{}) *MockCacher_Set_Call {
	return &MockCacher_Set_Call{Call: _e.mock.On("Set", ctx, key, value, expiration)}
}

func (_c *MockCacher_Set_Call) Run(run func(ctx context.Context, key string, value any, expiration time.Duration)) *MockCacher_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCacher_Set_Call) Return(err error) *MockCacher_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCacher_Set_Call) RunAndReturn(run func(ctx context.Context, key string, value any, expiration time.Duration) error) *MockCacher_Set_Call {
	_c.Call.Return(run)
	return _c
}
