// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package openrest

import (
	"context"

	"github.com/PritOriginal/problem-map-server/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStats creates a new instance of MockStats. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStats(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStats {
	mock := &MockStats{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStats is an autogenerated mock type for the Stats type
type MockStats struct {
	mock.Mock
}

type MockStats_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStats) EXPECT() *MockStats_Expecter {
	return &MockStats_Expecter{mock: &_m.Mock}
}

// GetOpenStats provides a mock function for the type MockStats
func (_mock *MockStats) GetOpenStats(ctx context.Context, boundaryID int) (models.OpenStats, error) {
	ret := _mock.Called(ctx, boundaryID)

	if len(ret) == 0 {
		panic("no return value specified for GetOpenStats")
	}

	var r0 models.OpenStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (models.OpenStats, error)); ok {
		return returnFunc(ctx, boundaryID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) models.OpenStats); ok {
		r0 = returnFunc(ctx, boundaryID)
	} else {
		r0 = ret.Get(0).(models.OpenStats)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, boundaryID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStats_GetOpenStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOpenStats'
type MockStats_GetOpenStats_Call struct {
	*mock.Call
}

// GetOpenStats is a helper method to define mock.On call
//   - ctx context.Context
//   - boundaryID int
func (_e *MockStats_Expecter) GetOpenStats(ctx any, boundaryID any) *MockStats_GetOpenStats_Call {
	return &MockStats_GetOpenStats_Call{Call: _e.mock.On("GetOpenStats", ctx, boundaryID)}
}

func (_c *MockStats_GetOpenStats_Call) Run(run func(ctx context.Context, boundaryID int)) *MockStats_GetOpenStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStats_GetOpenStats_Call) Return(openStats models.OpenStats, err error) *MockStats_GetOpenStats_Call {
	_c.Call.Return(openStats, err)
	return _c
}

func (_c *MockStats_GetOpenStats_Call) RunAndReturn(run func(ctx context.Context, boundaryID int) (models.OpenStats, error)) *MockStats_GetOpenStats_Call {
	_c.Call.Return(run)
	return _c
}
