// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ratelimit

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCounter creates a new instance of MockCounter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCounter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCounter {
	mock := &MockCounter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCounter is an autogenerated mock type for the Counter type
type MockCounter struct {
	mock.Mock
}

type MockCounter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCounter) EXPECT() *MockCounter_Expecter {
	return &MockCounter_Expecter{mock: &_m.Mock}
}

// Incr provides a mock function for the type MockCounter
func (_mock *MockCounter) Incr(ctx context.Context, key string, window time.Duration) (int64, time.Duration, error) {
	ret := _mock.Called(ctx, key, window)

	if len(ret) == 0 {
		panic("no return value specified for Incr")
	}

	var r0 int64
	var r1 time.Duration
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) (int64, time.Duration, error)); ok {
		return returnFunc(ctx, key, window)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) int64); ok {
		r0 = returnFunc(ctx, key, window)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Duration) time.Duration); ok {
		r1 = returnFunc(ctx, key, window)
	} else {
		r1 = ret.Get(1).(time.Duration)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, time.Duration) error); ok {
		r2 = returnFunc(ctx, key, window)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockCounter_Incr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Incr'
type MockCounter_Incr_Call struct {
	*mock.Call
}

// Incr is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - window time.Duration
func (_e *MockCounter_Expecter) Incr(ctx any, key any, window any) *MockCounter_Incr_Call {
	return &MockCounter_Incr_Call{Call: _e.mock.On("Incr", ctx, key, window)}
}

func (_c *MockCounter_Incr_Call) Run(run func(ctx context.Context, key string, window time.Duration)) *MockCounter_Incr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCounter_Incr_Call) Return(count int64, ttl time.Duration, err error) *MockCounter_Incr_Call {
	_c.Call.Return(count, ttl, err)
	return _c
}

func (_c *MockCounter_Incr_Call) RunAndReturn(run func(ctx context.Context, key string, window time.Duration) (int64, time.Duration, error)) *MockCounter_Incr_Call {
	_c.Call.Return(run)
	return _c
}
