// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/signin": {
            "post": {
                "description": "sign in user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Sign In",
                "parameters": [
                    {
                        "description": "query params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_auth.SignInRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_auth_SignInResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    }
                }
            }
        },
        "/auth/signup": {
            "post": {
                "description": "sign up a new user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Sign Up",
                "parameters": [
                    {
                        "description": "query params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_auth.SignUpRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_auth_SignUpResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    }
                }
            }
        },
        "/auth/tokens/refresh": {
            "post": {
                "description": "refresh access and refresh tokens",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Refresh tokens",
                "parameters": [
                    {
                        "description": "query params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_auth.RefreshTokensRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_auth_RefreshTokensResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    }
                }
            }
        },
        "/checks": {
            "post": {
                "description": "add check",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "checks"
                ],
                "summary": "Add check",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_checks_AddCheckResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    }
                }
            }
        },
        "/checks/mark/{id}": {
            "get": {
                "description": "get check by mark id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "checks"
                ],
                "summary": "Get check by mark id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "mark id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_checks_GetChecksByMarkIdResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    }
                }
            }
        },
        "/checks/user/{id}": {
            "get": {
                "description": "get checks by user id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "checks"
                ],
                "summary": "List checks by user id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "user id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_checks_GetChecksByUserIdResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    }
                }
            }
        },
        "/checks/{id}": {
            "get": {
                "description": "get check by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "checks"
                ],
                "summary": "Get check by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "check id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_checks_GetCheckByIdResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    }
                }
            }
        },
        "/map/admin-boundaries": {
            "get": {
                "description": "admin boundaries",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "map"
                ],
                "summary": "List administrative boundaries",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "number"
                        },
                        "collectionFormat": "csv",
                        "description": "filter by admin level",
                        "name": "admin_levels",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_map_GetAdminBoundariesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    }
                }
            }
        },
        "/map/admin-boundaries/marks/count": {
            "get": {
                "description": "the count of markers of all administrative boundaries",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "map"
                ],
                "summary": "The count of markers of all administrative boundaries",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "number"
                        },
                        "collectionFormat": "csv",
                        "description": "filter by admin level",
                        "name": "admin_levels",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "number"
                        },
                        "collectionFormat": "csv",
                        "description": "filter by mark type",
                        "name": "mark_type_ids",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_map_GetAdminBoundariesMarksCountResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    }
                }
            }
        },
        "/map/cities": {
            "get": {
                "description": "get cities",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "map"
                ],
                "summary": "List cities",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_map_GetCitiesResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    }
                }
            }
        },
        "/map/districts": {
            "get": {
                "description": "get districts",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "map"
                ],
                "summary": "List districts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_map_GetDistrictsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    }
                }
            }
        },
        "/map/regions": {
            "get": {
                "description": "get regions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "map"
                ],
                "summary": "List regions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_map_GetRegionsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    }
                }
            }
        },
        "/marks": {
            "get": {
                "description": "get markers",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "marks"
                ],
                "summary": "List markers",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "number"
                        },
                        "collectionFormat": "csv",
                        "description": "filter by mark types",
                        "name": "mark_type_ids",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "number"
                        },
                        "collectionFormat": "csv",
                        "description": "filter by mark statuses",
                        "name": "mark_status_ids",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_marks_GetMarksResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    }
                }
            },
            "post": {
                "description": "add mark",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "marks"
                ],
                "summary": "Add mark",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_marks_AddMarkResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    }
                }
            }
        },
        "/marks/statuses": {
            "get": {
                "description": "get mark statuses",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "marks"
                ],
                "summary": "List mark statuses",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_marks_GetMarkStatusesResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    }
                }
            }
        },
        "/marks/types": {
            "get": {
                "description": "get mark types",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "marks"
                ],
                "summary": "List mark types",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_marks_GetMarkTypesResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    }
                }
            }
        },
        "/marks/user/{id}": {
            "get": {
                "description": "get markers by user id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "marks"
                ],
                "summary": "List markers by user id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "user id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_marks_GetMarksByUserIdResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    }
                }
            }
        },
        "/marks/{id}": {
            "get": {
                "description": "get mark by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "marks"
                ],
                "summary": "Get mark by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "mark id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_marks_GetMarkByIdResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    }
                }
            }
        },
        "/marks/{id}/status-history": {
            "get": {
                "description": "displays the entire list of status changes history for a specific marker by markId",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "marks"
                ],
                "summary": "List mark statuses",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "mark id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "with checks",
                        "name": "withChecks",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_marks_GetMarkStatusHistoryByMarkIdResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    }
                }
            }
        },
        "/tasks": {
            "get": {
                "description": "get tasks",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "List tasks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_tasks_GetTasksResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    }
                }
            },
            "post": {
                "description": "add new task",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Add task",
                "parameters": [
                    {
                        "description": "query params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_tasks.AddTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_tasks_AddTaskResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    }
                }
            }
        },
        "/tasks/user/{id}": {
            "get": {
                "description": "get tasks by user id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Get tasks by user id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "user id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_tasks_GetTasksByUserIdResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    }
                }
            }
        },
        "/tasks/{id}": {
            "get": {
                "description": "get task by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Get task by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "task id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_tasks_GetTaskByIdResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "get users",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "List users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_users_GetUsersResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "description": "get user by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "user id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_users_GetUserByIdResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.Response-any"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_PritOriginal_problem-map-server_internal_models.AdminBoundary": {
            "type": "object",
            "properties": {
                "admin_level": {
                    "type": "integer"
                },
                "geom": {
                    "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_internal_models.MultiPolygonJSON"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_PritOriginal_problem-map-server_internal_models.AdminBoundaryMarksCount": {
            "type": "object",
            "properties": {
                "closed_count": {
                    "type": "integer"
                },
                "confirmed_count": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "total_count": {
                    "type": "integer"
                },
                "unconfirmed_count": {
                    "type": "integer"
                },
                "under_review_count": {
                    "type": "integer"
                }
            }
        },
        "github_com_PritOriginal_problem-map-server_internal_models.Check": {
            "type": "object",
            "properties": {
                "check_id": {
                    "type": "integer"
                },
                "comment": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "mark_id": {
                    "type": "integer"
                },
                "mark_status_history_id": {
                    "type": "integer"
                },
                "mark_status_id": {
                    "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_internal_models.MarkStatusType"
                },
                "photos": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "result": {
                    "type": "boolean"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_PritOriginal_problem-map-server_internal_models.City": {
            "type": "object",
            "properties": {
                "city_id": {
                    "type": "integer"
                },
                "geom": {
                    "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_internal_models.PolygonJSON"
                },
                "name": {
                    "type": "string"
                },
                "region_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_PritOriginal_problem-map-server_internal_models.District": {
            "type": "object",
            "properties": {
                "city_id": {
                    "type": "integer"
                },
                "district_id": {
                    "type": "integer"
                },
                "geom": {
                    "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_internal_models.PolygonJSON"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_PritOriginal_problem-map-server_internal_models.Mark": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "geom": {
                    "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_internal_models.PointJSON"
                },
                "mark_id": {
                    "type": "integer"
                },
                "mark_status_id": {
                    "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_internal_models.MarkStatusType"
                },
                "mark_type_id": {
                    "type": "integer"
                },
                "number_checks": {
                    "type": "integer"
                },
                "number_votes": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_PritOriginal_problem-map-server_internal_models.MarkStatus": {
            "type": "object",
            "properties": {
                "mark_status_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "parent_id": {
                    "$ref": "#/definitions/null.Int"
                }
            }
        },
        "github_com_PritOriginal_problem-map-server_internal_models.MarkStatusHistoryItem": {
            "type": "object",
            "properties": {
                "changed_at": {
                    "type": "string"
                },
                "checks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_internal_models.Check"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "mark_id": {
                    "type": "integer"
                },
                "new_mark_status_id": {
                    "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_internal_models.MarkStatusType"
                },
                "old_mark_status_id": {
                    "$ref": "#/definitions/null.Value-github_com_PritOriginal_problem-map-server_internal_models_MarkStatusType"
                },
                "prev_id": {
                    "$ref": "#/definitions/null.Int"
                }
            }
        },
        "github_com_PritOriginal_problem-map-server_internal_models.MarkStatusType": {
            "type": "integer",
            "enum": [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "x-enum-varnames": [
                "UnconfirmedStatus",
                "ConfirmedStatus",
                "UnderReviewStatus",
                "RediscoveredStatus",
                "ClosedStatus",
                "RefutedStatus"
            ]
        },
        "github_com_PritOriginal_problem-map-server_internal_models.MarkType": {
            "type": "object",
            "properties": {
                "mark_type_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_PritOriginal_problem-map-server_internal_models.MultiPolygonJSON": {
            "type": "object",
            "properties": {
                "coordinates": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "type": "number",
                                    "format": "float64"
                                }
                            }
                        }
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_PritOriginal_problem-map-server_internal_models.PointJSON": {
            "type": "object",
            "properties": {
                "coordinates": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    },
                    "example": [
                        0,
                        0
                    ]
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_PritOriginal_problem-map-server_internal_models.PolygonJSON": {
            "type": "object",
            "properties": {
                "coordinates": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "number",
                            "format": "float64"
                        }
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_PritOriginal_problem-map-server_internal_models.Region": {
            "type": "object",
            "properties": {
                "geom": {
                    "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_internal_models.PolygonJSON"
                },
                "name": {
                    "type": "string"
                },
                "region_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_PritOriginal_problem-map-server_internal_models.Task": {
            "type": "object",
            "properties": {
                "mark_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "status_id": {
                    "type": "integer"
                },
                "task_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_PritOriginal_problem-map-server_internal_models.User": {
            "type": "object",
            "properties": {
                "home_point": {
                    "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_internal_models.PointJSON"
                },
                "login": {
                    "type": "string"
                },
                "rating": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_PritOriginal_problem-map-server_pkg_responses.ErrorInfo": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_PritOriginal_problem-map-server_pkg_responses.Response-any": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.ErrorInfo"
                },
                "payload": {},
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_auth_RefreshTokensResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.ErrorInfo"
                },
                "payload": {
                    "$ref": "#/definitions/internal_handler_auth.RefreshTokensResponse"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_auth_SignInResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.ErrorInfo"
                },
                "payload": {
                    "$ref": "#/definitions/internal_handler_auth.SignInResponse"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_auth_SignUpResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.ErrorInfo"
                },
                "payload": {
                    "$ref": "#/definitions/internal_handler_auth.SignUpResponse"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_checks_AddCheckResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.ErrorInfo"
                },
                "payload": {
                    "$ref": "#/definitions/internal_handler_checks.AddCheckResponse"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_checks_GetCheckByIdResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.ErrorInfo"
                },
                "payload": {
                    "$ref": "#/definitions/internal_handler_checks.GetCheckByIdResponse"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_checks_GetChecksByMarkIdResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.ErrorInfo"
                },
                "payload": {
                    "$ref": "#/definitions/internal_handler_checks.GetChecksByMarkIdResponse"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_checks_GetChecksByUserIdResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.ErrorInfo"
                },
                "payload": {
                    "$ref": "#/definitions/internal_handler_checks.GetChecksByUserIdResponse"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_map_GetAdminBoundariesMarksCountResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.ErrorInfo"
                },
                "payload": {
                    "$ref": "#/definitions/internal_handler_map.GetAdminBoundariesMarksCountResponse"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_map_GetAdminBoundariesResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.ErrorInfo"
                },
                "payload": {
                    "$ref": "#/definitions/internal_handler_map.GetAdminBoundariesResponse"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_map_GetCitiesResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.ErrorInfo"
                },
                "payload": {
                    "$ref": "#/definitions/internal_handler_map.GetCitiesResponse"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_map_GetDistrictsResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.ErrorInfo"
                },
                "payload": {
                    "$ref": "#/definitions/internal_handler_map.GetDistrictsResponse"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_map_GetRegionsResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.ErrorInfo"
                },
                "payload": {
                    "$ref": "#/definitions/internal_handler_map.GetRegionsResponse"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_marks_AddMarkResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.ErrorInfo"
                },
                "payload": {
                    "$ref": "#/definitions/internal_handler_marks.AddMarkResponse"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_marks_GetMarkByIdResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.ErrorInfo"
                },
                "payload": {
                    "$ref": "#/definitions/internal_handler_marks.GetMarkByIdResponse"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_marks_GetMarkStatusHistoryByMarkIdResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.ErrorInfo"
                },
                "payload": {
                    "$ref": "#/definitions/internal_handler_marks.GetMarkStatusHistoryByMarkIdResponse"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_marks_GetMarkStatusesResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.ErrorInfo"
                },
                "payload": {
                    "$ref": "#/definitions/internal_handler_marks.GetMarkStatusesResponse"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_marks_GetMarkTypesResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.ErrorInfo"
                },
                "payload": {
                    "$ref": "#/definitions/internal_handler_marks.GetMarkTypesResponse"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_marks_GetMarksByUserIdResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.ErrorInfo"
                },
                "payload": {
                    "$ref": "#/definitions/internal_handler_marks.GetMarksByUserIdResponse"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_marks_GetMarksResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.ErrorInfo"
                },
                "payload": {
                    "$ref": "#/definitions/internal_handler_marks.GetMarksResponse"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_tasks_AddTaskResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.ErrorInfo"
                },
                "payload": {
                    "$ref": "#/definitions/internal_handler_tasks.AddTaskResponse"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_tasks_GetTaskByIdResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.ErrorInfo"
                },
                "payload": {
                    "$ref": "#/definitions/internal_handler_tasks.GetTaskByIdResponse"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_tasks_GetTasksByUserIdResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.ErrorInfo"
                },
                "payload": {
                    "$ref": "#/definitions/internal_handler_tasks.GetTasksByUserIdResponse"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_tasks_GetTasksResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.ErrorInfo"
                },
                "payload": {
                    "$ref": "#/definitions/internal_handler_tasks.GetTasksResponse"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_users_GetUserByIdResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.ErrorInfo"
                },
                "payload": {
                    "$ref": "#/definitions/internal_handler_users.GetUserByIdResponse"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_PritOriginal_problem-map-server_pkg_responses.Response-internal_handler_users_GetUsersResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_pkg_responses.ErrorInfo"
                },
                "payload": {
                    "$ref": "#/definitions/internal_handler_users.GetUsersResponse"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "internal_handler_auth.RefreshTokensRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "internal_handler_auth.RefreshTokensResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "internal_handler_auth.SignInRequest": {
            "type": "object",
            "required": [
                "login",
                "password"
            ],
            "properties": {
                "login": {
                    "type": "string",
                    "maxLength": 40,
                    "minLength": 3
                },
                "password": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 8
                }
            }
        },
        "internal_handler_auth.SignInResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "internal_handler_auth.SignUpRequest": {
            "type": "object",
            "required": [
                "login",
                "password",
                "username"
            ],
            "properties": {
                "login": {
                    "type": "string",
                    "maxLength": 40,
                    "minLength": 3
                },
                "password": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 8
                },
                "username": {
                    "type": "string",
                    "maxLength": 40,
                    "minLength": 2
                }
            }
        },
        "internal_handler_auth.SignUpResponse": {
            "type": "object",
            "properties": {
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "internal_handler_checks.AddCheckResponse": {
            "type": "object",
            "properties": {
                "check_id": {
                    "type": "integer"
                }
            }
        },
        "internal_handler_checks.GetCheckByIdResponse": {
            "type": "object",
            "properties": {
                "check": {
                    "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_internal_models.Check"
                }
            }
        },
        "internal_handler_checks.GetChecksByMarkIdResponse": {
            "type": "object",
            "properties": {
                "checks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_internal_models.Check"
                    }
                }
            }
        },
        "internal_handler_checks.GetChecksByUserIdResponse": {
            "type": "object",
            "properties": {
                "checks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_internal_models.Check"
                    }
                }
            }
        },
        "internal_handler_map.GetAdminBoundariesMarksCountResponse": {
            "type": "object",
            "properties": {
                "admin_boundaries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_internal_models.AdminBoundaryMarksCount"
                    }
                }
            }
        },
        "internal_handler_map.GetAdminBoundariesResponse": {
            "type": "object",
            "properties": {
                "admin_boundaries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_internal_models.AdminBoundary"
                    }
                }
            }
        },
        "internal_handler_map.GetCitiesResponse": {
            "type": "object",
            "properties": {
                "cities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_internal_models.City"
                    }
                }
            }
        },
        "internal_handler_map.GetDistrictsResponse": {
            "type": "object",
            "properties": {
                "districts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_internal_models.District"
                    }
                }
            }
        },
        "internal_handler_map.GetRegionsResponse": {
            "type": "object",
            "properties": {
                "regions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_internal_models.Region"
                    }
                }
            }
        },
        "internal_handler_marks.AddMarkResponse": {
            "type": "object",
            "properties": {
                "mark_id": {
                    "type": "integer"
                }
            }
        },
        "internal_handler_marks.GetMarkByIdResponse": {
            "type": "object",
            "properties": {
                "mark": {
                    "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_internal_models.Mark"
                }
            }
        },
        "internal_handler_marks.GetMarkStatusHistoryByMarkIdResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_internal_models.MarkStatusHistoryItem"
                    }
                }
            }
        },
        "internal_handler_marks.GetMarkStatusesResponse": {
            "type": "object",
            "properties": {
                "mark_statuses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_internal_models.MarkStatus"
                    }
                }
            }
        },
        "internal_handler_marks.GetMarkTypesResponse": {
            "type": "object",
            "properties": {
                "mark_types": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_internal_models.MarkType"
                    }
                }
            }
        },
        "internal_handler_marks.GetMarksByUserIdResponse": {
            "type": "object",
            "properties": {
                "marks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_internal_models.Mark"
                    }
                }
            }
        },
        "internal_handler_marks.GetMarksResponse": {
            "type": "object",
            "properties": {
                "marks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_internal_models.Mark"
                    }
                }
            }
        },
        "internal_handler_tasks.AddTaskRequest": {
            "type": "object",
            "required": [
                "mark_id",
                "name",
                "user_id"
            ],
            "properties": {
                "mark_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "internal_handler_tasks.AddTaskResponse": {
            "type": "object",
            "properties": {
                "task_id": {
                    "type": "integer"
                }
            }
        },
        "internal_handler_tasks.GetTaskByIdResponse": {
            "type": "object",
            "properties": {
                "task": {
                    "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_internal_models.Task"
                }
            }
        },
        "internal_handler_tasks.GetTasksByUserIdResponse": {
            "type": "object",
            "properties": {
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_internal_models.Task"
                    }
                }
            }
        },
        "internal_handler_tasks.GetTasksResponse": {
            "type": "object",
            "properties": {
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_internal_models.Task"
                    }
                }
            }
        },
        "internal_handler_users.GetUserByIdResponse": {
            "type": "object",
            "properties": {
                "user": {
                    "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_internal_models.User"
                }
            }
        },
        "internal_handler_users.GetUsersResponse": {
            "type": "object",
            "properties": {
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_internal_models.User"
                    }
                }
            }
        },
        "null.Int": {
            "type": "object",
            "properties": {
                "int64": {
                    "type": "integer",
                    "format": "int64"
                },
                "valid": {
                    "description": "Valid is true if Int64 is not NULL",
                    "type": "boolean"
                }
            }
        },
        "null.Value-github_com_PritOriginal_problem-map-server_internal_models_MarkStatusType": {
            "type": "object",
            "properties": {
                "v": {
                    "$ref": "#/definitions/github_com_PritOriginal_problem-map-server_internal_models.MarkStatusType"
                },
                "valid": {
                    "type": "boolean"
                }
            }
        }
    },
    "tags": [
        {
            "description": "Authorization and authentication",
            "name": "auth"
        },
        {
            "description": "Operations with geodata",
            "name": "map"
        },
        {
            "description": "Operations with markers",
            "name": "marks"
        },
        {
            "description": "Operations with checks",
            "name": "checks"
        },
        {
            "description": "Operations with tasks",
            "name": "tasks"
        },
        {
            "description": "Operations with users",
            "name": "users"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Problem Map API",
	Description:      "This is the API documentation for the \"Problem Map\" project.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
