// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package nats

import (
	"context"

	"github.com/nats-io/nats.go"
	"github.com/nats-io/nats.go/jetstream"
	mock "github.com/stretchr/testify/mock"
)

// newMockidentified creates a new instance of mockidentified. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockidentified(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockidentified {
	mock := &mockidentified{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockidentified is an autogenerated mock type for the identified type
type mockidentified struct {
	mock.Mock
}

type mockidentified_Expecter struct {
	mock *mock.Mock
}

func (_m *mockidentified) EXPECT() *mockidentified_Expecter {
	return &mockidentified_Expecter{mock: &_m.Mock}
}

// ID provides a mock function for the type mockidentified
func (_mock *mockidentified) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// mockidentified_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type mockidentified_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *mockidentified_Expecter) ID() *mockidentified_ID_Call {
	return &mockidentified_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *mockidentified_ID_Call) Run(run func()) *mockidentified_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockidentified_ID_Call) Return(s string) *mockidentified_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *mockidentified_ID_Call) RunAndReturn(run func() string) *mockidentified_ID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDLQPublisher creates a new instance of MockDLQPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDLQPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDLQPublisher {
	mock := &MockDLQPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDLQPublisher is an autogenerated mock type for the DLQPublisher type
type MockDLQPublisher struct {
	mock.Mock
}

type MockDLQPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDLQPublisher) EXPECT() *MockDLQPublisher_Expecter {
	return &MockDLQPublisher_Expecter{mock: &_m.Mock}
}

// PublishMsg provides a mock function for the type MockDLQPublisher
func (_mock *MockDLQPublisher) PublishMsg(ctx context.Context, msg *nats.Msg, opts ...jetstream.PublishOpt) (*jetstream.PubAck, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, msg, opts)
	} else {
		tmpRet = _mock.Called(ctx, msg)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PublishMsg")
	}

	var r0 *jetstream.PubAck
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *nats.Msg, ...jetstream.PublishOpt) (*jetstream.PubAck, error)); ok {
		return returnFunc(ctx, msg, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *nats.Msg, ...jetstream.PublishOpt) *jetstream.PubAck); ok {
		r0 = returnFunc(ctx, msg, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jetstream.PubAck)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *nats.Msg, ...jetstream.PublishOpt) error); ok {
		r1 = returnFunc(ctx, msg, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDLQPublisher_PublishMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishMsg'
type MockDLQPublisher_PublishMsg_Call struct {
	*mock.Call
}

// PublishMsg is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *nats.Msg
//   - opts ...jetstream.PublishOpt
func (_e *MockDLQPublisher_Expecter) PublishMsg(ctx any, msg any, opts ...any) *MockDLQPublisher_PublishMsg_Call {
	return &MockDLQPublisher_PublishMsg_Call{Call: _e.mock.On("PublishMsg",
		append([]any{ctx, msg}, opts...)...)}
}

func (_c *MockDLQPublisher_PublishMsg_Call) Run(run func(ctx context.Context, msg *nats.Msg, opts ...jetstream.PublishOpt)) *MockDLQPublisher_PublishMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *nats.Msg
		if args[1] != nil {
			arg1 = args[1].(*nats.Msg)
		}
		var arg2 []jetstream.PublishOpt
		var variadicArgs []jetstream.PublishOpt
		if len(args) > 2 {
			variadicArgs = args[2].([]jetstream.PublishOpt)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockDLQPublisher_PublishMsg_Call) Return(pubAck *jetstream.PubAck, err error) *MockDLQPublisher_PublishMsg_Call {
	_c.Call.Return(pubAck, err)
	return _c
}

func (_c *MockDLQPublisher_PublishMsg_Call) RunAndReturn(run func(ctx context.Context, msg *nats.Msg, opts ...jetstream.PublishOpt) (*jetstream.PubAck, error)) *MockDLQPublisher_PublishMsg_Call {
	_c.Call.Return(run)
	return _c
}
