// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package achievementsrest

import (
	"context"

	"github.com/PritOriginal/problem-map-server/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAchievements creates a new instance of MockAchievements. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAchievements(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAchievements {
	mock := &MockAchievements{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAchievements is an autogenerated mock type for the Achievements type
type MockAchievements struct {
	mock.Mock
}

type MockAchievements_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAchievements) EXPECT() *MockAchievements_Expecter {
	return &MockAchievements_Expecter{mock: &_m.Mock}
}

// GetProfile provides a mock function for the type MockAchievements
func (_mock *MockAchievements) GetProfile(ctx context.Context, userId int) (models.UserProfile, error) {
	ret := _mock.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 models.UserProfile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (models.UserProfile, error)); ok {
		return returnFunc(ctx, userId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) models.UserProfile); ok {
		r0 = returnFunc(ctx, userId)
	} else {
		r0 = ret.Get(0).(models.UserProfile)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAchievements_GetProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfile'
type MockAchievements_GetProfile_Call struct {
	*mock.Call
}

// GetProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userId int
func (_e *MockAchievements_Expecter) GetProfile(ctx any, userId any) *MockAchievements_GetProfile_Call {
	return &MockAchievements_GetProfile_Call{Call: _e.mock.On("GetProfile", ctx, userId)}
}

func (_c *MockAchievements_GetProfile_Call) Run(run func(ctx context.Context, userId int)) *MockAchievements_GetProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAchievements_GetProfile_Call) Return(userProfile models.UserProfile, err error) *MockAchievements_GetProfile_Call {
	_c.Call.Return(userProfile, err)
	return _c
}

func (_c *MockAchievements_GetProfile_Call) RunAndReturn(run func(ctx context.Context, userId int) (models.UserProfile, error)) *MockAchievements_GetProfile_Call {
	_c.Call.Return(run)
	return _c
}

// ListBadges provides a mock function for the type MockAchievements
func (_mock *MockAchievements) ListBadges(ctx context.Context) ([]models.Badge, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListBadges")
	}

	var r0 []models.Badge
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.Badge, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.Badge); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Badge)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAchievements_ListBadges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBadges'
type MockAchievements_ListBadges_Call struct {
	*mock.Call
}

// ListBadges is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAchievements_Expecter) ListBadges(ctx any) *MockAchievements_ListBadges_Call {
	return &MockAchievements_ListBadges_Call{Call: _e.mock.On("ListBadges", ctx)}
}

func (_c *MockAchievements_ListBadges_Call) Run(run func(ctx context.Context)) *MockAchievements_ListBadges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAchievements_ListBadges_Call) Return(badges []models.Badge, err error) *MockAchievements_ListBadges_Call {
	_c.Call.Return(badges, err)
	return _c
}

func (_c *MockAchievements_ListBadges_Call) RunAndReturn(run func(ctx context.Context) ([]models.Badge, error)) *MockAchievements_ListBadges_Call {
	_c.Call.Return(run)
	return _c
}
