// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package tasksrest

import (
	"context"

	"github.com/PritOriginal/problem-map-server/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTasks creates a new instance of MockTasks. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTasks(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTasks {
	mock := &MockTasks{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTasks is an autogenerated mock type for the Tasks type
type MockTasks struct {
	mock.Mock
}

type MockTasks_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTasks) EXPECT() *MockTasks_Expecter {
	return &MockTasks_Expecter{mock: &_m.Mock}
}

// AddTask provides a mock function for the type MockTasks
func (_mock *MockTasks) AddTask(ctx context.Context, task models.Task) (int64, error) {
	ret := _mock.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for AddTask")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Task) (int64, error)); ok {
		return returnFunc(ctx, task)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Task) int64); ok {
		r0 = returnFunc(ctx, task)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Task) error); ok {
		r1 = returnFunc(ctx, task)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTasks_AddTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTask'
type MockTasks_AddTask_Call struct {
	*mock.Call
}

// AddTask is a helper method to define mock.On call
//   - ctx context.Context
//   - task models.Task
func (_e *MockTasks_Expecter) AddTask(ctx interface{}, task interface{}) *MockTasks_AddTask_Call {
	return &MockTasks_AddTask_Call{Call: _e.mock.On("AddTask", ctx, task)}
}

func (_c *MockTasks_AddTask_Call) Run(run func(ctx context.Context, task models.Task)) *MockTasks_AddTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Task
		if args[1] != nil {
			arg1 = args[1].(models.Task)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTasks_AddTask_Call) Return(n int64, err error) *MockTasks_AddTask_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockTasks_AddTask_Call) RunAndReturn(run func(ctx context.Context, task models.Task) (int64, error)) *MockTasks_AddTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskById provides a mock function for the type MockTasks
func (_mock *MockTasks) GetTaskById(ctx context.Context, id int) (models.Task, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskById")
	}

	var r0 models.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (models.Task, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) models.Task); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTasks_GetTaskById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskById'
type MockTasks_GetTaskById_Call struct {
	*mock.Call
}

// GetTaskById is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockTasks_Expecter) GetTaskById(ctx interface{}, id interface{}) *MockTasks_GetTaskById_Call {
	return &MockTasks_GetTaskById_Call{Call: _e.mock.On("GetTaskById", ctx, id)}
}

func (_c *MockTasks_GetTaskById_Call) Run(run func(ctx context.Context, id int)) *MockTasks_GetTaskById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTasks_GetTaskById_Call) Return(task models.Task, err error) *MockTasks_GetTaskById_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockTasks_GetTaskById_Call) RunAndReturn(run func(ctx context.Context, id int) (models.Task, error)) *MockTasks_GetTaskById_Call {
	_c.Call.Return(run)
	return _c
}

// GetTasks provides a mock function for the type MockTasks
func (_mock *MockTasks) GetTasks(ctx context.Context) ([]models.Task, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTasks")
	}

	var r0 []models.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.Task, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.Task); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTasks_GetTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTasks'
type MockTasks_GetTasks_Call struct {
	*mock.Call
}

// GetTasks is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTasks_Expecter) GetTasks(ctx interface{}) *MockTasks_GetTasks_Call {
	return &MockTasks_GetTasks_Call{Call: _e.mock.On("GetTasks", ctx)}
}

func (_c *MockTasks_GetTasks_Call) Run(run func(ctx context.Context)) *MockTasks_GetTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTasks_GetTasks_Call) Return(tasks []models.Task, err error) *MockTasks_GetTasks_Call {
	_c.Call.Return(tasks, err)
	return _c
}

func (_c *MockTasks_GetTasks_Call) RunAndReturn(run func(ctx context.Context) ([]models.Task, error)) *MockTasks_GetTasks_Call {
	_c.Call.Return(run)
	return _c
}

// GetTasksByUserId provides a mock function for the type MockTasks
func (_mock *MockTasks) GetTasksByUserId(ctx context.Context, userId int) ([]models.Task, error) {
	ret := _mock.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetTasksByUserId")
	}

	var r0 []models.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]models.Task, error)); ok {
		return returnFunc(ctx, userId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []models.Task); ok {
		r0 = returnFunc(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTasks_GetTasksByUserId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTasksByUserId'
type MockTasks_GetTasksByUserId_Call struct {
	*mock.Call
}

// GetTasksByUserId is a helper method to define mock.On call
//   - ctx context.Context
//   - userId int
func (_e *MockTasks_Expecter) GetTasksByUserId(ctx interface{}, userId interface{}) *MockTasks_GetTasksByUserId_Call {
	return &MockTasks_GetTasksByUserId_Call{Call: _e.mock.On("GetTasksByUserId", ctx, userId)}
}

func (_c *MockTasks_GetTasksByUserId_Call) Run(run func(ctx context.Context, userId int)) *MockTasks_GetTasksByUserId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTasks_GetTasksByUserId_Call) Return(tasks []models.Task, err error) *MockTasks_GetTasksByUserId_Call {
	_c.Call.Return(tasks, err)
	return _c
}

func (_c *MockTasks_GetTasksByUserId_Call) RunAndReturn(run func(ctx context.Context, userId int) ([]models.Task, error)) *MockTasks_GetTasksByUserId_Call {
	_c.Call.Return(run)
	return _c
}
