name: Tests Workflow
on:
  pull_request:
  workflow_call:
  
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4  

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      
      - name: Build
        run: |
          go build ./cmd/...

      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest

      - name: Start tests
        run: |
          go test -tags=nomsgpack -race -cover ./...
