// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usersrest

import (
	"context"

	"github.com/PritOriginal/problem-map-server/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUsers creates a new instance of MockUsers. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsers(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsers {
	mock := &MockUsers{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUsers is an autogenerated mock type for the Users type
type MockUsers struct {
	mock.Mock
}

type MockUsers_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsers) EXPECT() *MockUsers_Expecter {
	return &MockUsers_Expecter{mock: &_m.Mock}
}

// GetUserById provides a mock function for the type MockUsers
func (_mock *MockUsers) GetUserById(ctx context.Context, id int) (models.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserById")
	}

	var r0 models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (models.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) models.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(models.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsers_GetUserById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserById'
type MockUsers_GetUserById_Call struct {
	*mock.Call
}

// GetUserById is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockUsers_Expecter) GetUserById(ctx any, id any) *MockUsers_GetUserById_Call {
	return &MockUsers_GetUserById_Call{Call: _e.mock.On("GetUserById", ctx, id)}
}

func (_c *MockUsers_GetUserById_Call) Run(run func(ctx context.Context, id int)) *MockUsers_GetUserById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsers_GetUserById_Call) Return(user models.User, err error) *MockUsers_GetUserById_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUsers_GetUserById_Call) RunAndReturn(run func(ctx context.Context, id int) (models.User, error)) *MockUsers_GetUserById_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function for the type MockUsers
func (_mock *MockUsers) ListUsers(ctx context.Context, p models.Pagination) (models.Page[models.User], error) {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 models.Page[models.User]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Pagination) (models.Page[models.User], error)); ok {
		return returnFunc(ctx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Pagination) models.Page[models.User]); ok {
		r0 = returnFunc(ctx, p)
	} else {
		r0 = ret.Get(0).(models.Page[models.User])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Pagination) error); ok {
		r1 = returnFunc(ctx, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsers_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type MockUsers_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - p models.Pagination
func (_e *MockUsers_Expecter) ListUsers(ctx any, p any) *MockUsers_ListUsers_Call {
	return &MockUsers_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx, p)}
}

func (_c *MockUsers_ListUsers_Call) Run(run func(ctx context.Context, p models.Pagination)) *MockUsers_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Pagination
		if args[1] != nil {
			arg1 = args[1].(models.Pagination)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsers_ListUsers_Call) Return(page models.Page[models.User], err error) *MockUsers_ListUsers_Call {
	_c.Call.Return(page, err)
	return _c
}

func (_c *MockUsers_ListUsers_Call) RunAndReturn(run func(ctx context.Context, p models.Pagination) (models.Page[models.User], error)) *MockUsers_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}
